export type Role = 'admin'|'receiving'|'warehouse'|'planning'|'production'|'qc'|'laboratory'|'dispatch'|'management';
export const roles: {id:Role;name:string;person:string;description:string}[] = [
{id:'admin',name:'Administrator',person:'Demo Administrator',description:'All departments, master data and workflow controls'},
{id:'receiving',name:'Receiving',person:'Receiving Officer',description:'Incoming materials, supplier lots and inspection requests'},
{id:'warehouse',name:'Warehouse',person:'Warehouse Officer',description:'Stock, material issues, cold rooms and FG receipts'},
{id:'planning',name:'Planning',person:'Planning Officer',description:'Production orders, batch targets and requirements'},
{id:'production',name:'Production',person:'Production Operator',description:'Preparation, processing, cooking and packing'},
{id:'qc',name:'Quality Control',person:'QC Manager',description:'Inspection, release, holds and corrective actions'},
{id:'laboratory',name:'Laboratory',person:'Laboratory Analyst',description:'Water, swab and finished-product testing'},
{id:'dispatch',name:'Dispatch',person:'Dispatch Officer',description:'Vehicle checks, customer deliveries and lot allocation'},
{id:'management',name:'Management',person:'Factory Manager',description:'Read-only oversight, traceability and reports'}
];
export type Field = {key:string;label:string;type:string;options?:string[];required?:boolean;hint?:string};
export type Section = {id:string;title:string;fields:Field[];repeat?:boolean;initial?:Record<string,string>[]};
export type FormDef={id:string;name:string;short:string;department:Role;creators:Role[];reviewers:Role[];page:number|null;code:string;retention:string;description:string;sections:Section[];batch?:boolean;effect?:string};
const key=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
export function f(label:string,type='text',options?:string[],required=false):Field{return {key:key(label),label,type,options,required};}
const n=(s:string,req=false)=>f(s,'number',undefined,req),d=(s:string,req=false)=>f(s,'date',undefined,req),t=(s:string)=>f(s,'time'),s=(label:string,values:string[],req=false)=>f(label,'select',values,req),txt=(label:string,req=false)=>f(label,'text',undefined,req),memo=(label:string)=>f(label,'textarea');
const yes=['Yes','No','N/A'],pass=['Pass','Not pass','Not tested','N/A'];
const sec=(id:string,title:string,fields:Field[],repeat=false,initial?:Record<string,string>[]):Section=>({id,title,fields,repeat,initial});
const sign=sec('sign','Review and remarks',[memo('Remarks'),txt('Recorded by'),txt('Checked by'),txt('Reviewed by'),txt('Approved by')]);
const inspection=['General / Size','Color','Smell / Weight','Cleanliness / Plastic type','Other / Sizing / Seal','Biological','Chemical','Physical','Product ID / Color printing','Packaging','Delivery'];
export const forms:FormDef[]=[
{id:'receiving',name:'Material Receiving Report',short:'Material receiving',department:'receiving',creators:['receiving','qc'],reviewers:['qc'],page:2,code:'REC/QC-004',retention:'2 years (source)',description:'Record deliveries and lot-level inspection before material release.',effect:'Approval adds each material lot to released inventory.',sections:[
sec('header','Delivery details',[s('Raw material type',['Meat','Non-Meat','Packaging','Chemical','Others'],true),txt('Material name',true),txt('Specification number'),d('Receiving date',true),txt('PO number'),txt('Challan number'),txt('Receiving number'),txt('Supplier / source',true),txt('QC inspector'),txt('Truck / car number'),txt('Sampling number'),txt('Storage location',true)]),
sec('lots','Material lots',[txt('Lot number',true),d('Manufacturing date',true),d('Expiry date',true),n('Quantity',true),s('Unit',['kg','g','pack','pcs','L'],true),n('Arrival temperature 1 (C)'),n('Arrival temperature 2 (C)'),n('Arrival temperature 3 (C)'),n('Arrival temperature 4 (C)')],true),
sec('inspection','Inspection results',[txt('Criterion',true),txt('Standard / specification'),...Array.from({length:13},(_,i)=>txt(`Sample ${i+1}`)),s('Conforming',yes,true)],true,inspection.map(x=>({criterion:x,standard_specification:'As approved specification'}))),
sec('decision','Disposition',[s('Quantity check',['On PO required','Less than actual','Other'],true),n('Actual quantity'),s('Quality result',pass,true),memo('Recommendation'),txt('NC lot number'),n('NC quantity'),memo('NC characteristic'),s('Action required',['None','Hold with card','Rejected','Conform for use'],true),txt('Hold card number'),memo('Results after action'),txt('Reported by')]),sign]},
{id:'vegetable',name:'Fresh Vegetable Cleaning Record',short:'Vegetable cleaning',department:'production',creators:['production','qc'],reviewers:['qc'],page:3,code:'REC/QC-037',retention:'6 months (source)',description:'Record washing, solution preparation and cleaning checks.',batch:true,sections:[sec('header','Cleaning session',[d('Date',true)]),sec('rows','Vegetable cleaning entries',[d('Receiving date',true),txt('Vegetable type',true),txt('Source lot'),s('First rinse with water',yes,true),n('Water (L)'),n('NaHCO3 (g)'),txt('NaHCO3 PDD code'),txt('Solution checked by'),...Array.from({length:6},(_,i)=>txt(`Dipping observation ${i+1}`)),memo('Deviation note'),s('Second rinse with water',yes,true),d('Label PDD'),txt('Best before'),memo('Remark')],true),sign]},
{id:'sieving',name:'Sieving Report',short:'Sieving',department:'production',creators:['production'],reviewers:['production','qc'],page:4,code:'REC/PX-008',retention:'6 months (source)',description:'Capture material weight, sieve checks and foreign-material findings.',batch:true,sections:[sec('header','Preparation details',[d('Date',true),txt('Scale code'),s('Location',['Premix preparation','Flour preparation','Test room','Other'],true)]),sec('rows','Sieving entries',[txt('Product code'),txt('Product / raw material',true),d('PDD'),txt('Source lot',true),n('Weight before sieving (g)',true),n('Weight after sieving (g)',true),s('Sieve condition before',pass,true),s('Sieve condition after',pass,true),memo('Corrective action'),s('Foreign material found',yes,true),memo('Foreign material details'),memo('Remarks')],true),sign]},
{id:'premix_check',name:'Premix Checking Report',short:'Premix checking',department:'production',creators:['production'],reviewers:['production','qc'],page:5,code:'REC/PX-009',retention:'6 months (source)',description:'Verify premix pack weights, labels and seals.',batch:true,sections:[sec('header','Check details',[d('Date',true),txt('Balance code')]),sec('rows','Premix observations',[txt('Production code / name',true),txt('Premix number',true),n('Standard weight (g)',true),n('Total packs produced',true),s('Labelling',pass,true),...Array.from({length:5},(_,i)=>n(`Weight observation ${i+1} (g)`)),s('Sealing',pass,true),txt('Lot / batch number',true)],true),sign]},
{id:'premix_prep',name:'Premix Preparation Monitoring Form',short:'Premix preparation',department:'production',creators:['production'],reviewers:['production'],page:6,code:'REC/PX-002',retention:'6 months (source)',description:'Versioned recipe ingredients and preparation checks for each premix batch.',batch:true,sections:[sec('header','Preparation details',[txt('Product name',true),txt('Product code'),n('Recipe batch size (kg)',true),n('Number of sets',true),d('Date',true),t('Time'),txt('Recipe version')]),sec('ingredients','Ingredients and target quantities',[txt('Premix code',true),txt('Ingredient name',true),n('Target weight (g)',true),txt('Ingredient lot'),d('Ingredient expiry'),memo('Remark')],true),sec('checks','Batch preparation checks',[txt('Premix code',true),txt('Ingredient name',true),txt('Prepared batch number',true),n('Actual weight (g)',true),s('Preparation verified',pass,true),txt('Checked by')],true),sign]},
{id:'water_lab',name:'Water & Swab Testing Report',short:'Water / swab testing',department:'laboratory',creators:['laboratory'],reviewers:['qc'],page:7,code:'REC/LAB-005',retention:'1 year (source)',description:'Microbial and chemical results for water, staff or equipment samples.',sections:[sec('header','Sample information',[s('Sample from',['Machine / Equipment SWAB','Staff SWAB','Water','Other'],true),txt('Other source'),d('Sample receiving date',true),d('Sample collection date',true),txt('Collected by'),txt('Analyzed by',true),d('Analysis date',true)]),sec('micro','Microbial test results',[txt('Sample number',true),txt('Source / product name',true),txt('Unit (CFU per cm2 or ml)'),txt('TPC'),txt('Coliform'),txt('E. coli'),txt('S. aureus'),txt('Listeria sp.'),txt('Approved standard reference'),s('Conclusion',pass,true),s('Correction needed',yes,true)],true),sec('chemical','Chemical test results',[txt('Sample number'),txt('Source name'),txt('Hardness standard (ppm)'),txt('Hardness actual (ppm)'),txt('DO standard (ppm)'),txt('DO actual (ppm)'),txt('pH standard'),txt('pH actual'),txt('TDS standard (ppm)'),txt('TDS actual (ppm)'),txt('Other parameter'),txt('Other standard'),txt('Other actual')],true),sec('correction','Corrective action',[memo('Recommended corrective action')]),sign]},
{id:'grinding',name:'Production Report: Meat Grinding',short:'Meat grinding',department:'production',creators:['production','qc'],reviewers:['qc'],page:8,code:'REC/QC-035',retention:'1 year (source)',description:'Track input meat, grinding settings and measured temperatures.',batch:true,sections:[sec('header','Production details',[d('Production date',true),s('Shift',['Day','Night'],true)]),sec('rows','Grinding entries',[t('Start time'),d('Debone meat date'),txt('Use for'),txt('Source lot',true),n('Meat input (kg)',true),n('Plate diameter (mm)'),n('Temperature after grinding (C)',true),txt('Grinding meat code'),txt('QC sign'),memo('Remark')],true),sign]},
{id:'nc_balance',name:'NC Use & Balance Record',short:'NC use and balance',department:'qc',creators:['qc','production'],reviewers:['qc'],page:9,code:'REC/QC-014',retention:'3 months (source)',description:'Track authorized rework quantities and the destination batch.',batch:true,effect:'Links source and destination batches; rejects overuse of approved rework.',sections:[sec('header','Record details',[d('Date',true)]),sec('rows','Rework consumption',[t('Time'),txt('Approved NC record ID',true),txt('Source batch',true),txt('NC product code'),txt('NC product name',true),d('NC production date'),n('Available quantity (kg)'),n('Quantity used (kg)',true),txt('Destination product',true),d('Destination production date'),txt('Destination batch',true),n('Balance (kg)'),txt('Recorded by')],true),sign]},
{id:'sausage',name:'Sausage Mixing & Linking Inspection',short:'Mixing and linking',department:'production',creators:['production','qc'],reviewers:['qc'],page:10,code:'REC/QC-051',retention:'1 year (source)',description:'Capture formulation inputs, silent-cutter settings and linking checks.',batch:true,sections:[sec('header','Production details',[txt('Product name',true),txt('Thermometer ID'),txt('Balance ID'),d('Production date',true),s('Shift',['Day','Night'],true)]),sec('ingredients','Silent cutter / ingredient inputs',[txt('Batch number',true),t('Start time'),t('Finish time'),n('Speed'),txt('Ingredient',true),n('Recipe quantity (kg)'),n('Actual quantity (kg)',true),txt('Source lot',true),d('DD / actual date'),n('Temperature (C)')],true),sec('linking','Auto-linking and dimensional checks',[txt('Batch number',true),t('Start time'),t('Finish time'),txt('Casing code'),txt('Horn number'),n('Length (cm)'),n('Diameter (mm)'),n('Weight (g)'),txt('Approved size specification'),memo('Remarks')],true),sign]},
{id:'nc',name:'Nonconforming Product Report',short:'Nonconforming product',department:'qc',creators:['qc','production','warehouse'],reviewers:['qc'],page:11,code:'REC/QC-021',retention:'1 year (source)',description:'Hold affected batches and record an authorized disposition.',batch:true,effect:'Submitting places the batch on hold. QC disposition controls release, rework or rejection.',sections:[sec('header','Nonconformance details',[txt('Product name',true),txt('Product code'),d('Report date',true),t('Time'),txt('Location'),s('Stage',['Raw material','Work in process','Finished goods','Return'],true),s('Occurrence',['During storage','During preparation','Other'],true),d('Production date'),d('Return date'),txt('Affected material lot'),txt('QC operator')]),sec('rows','Corrective action',[memo('NC characteristic'),n('Affected quantity (kg)',true),s('Disposition',['Hold','Release after correction','Approved rework','Scrap / reject'],true),memo('Correction method'),txt('Rework product'),txt('Destination batch'),d('Correction finished on'),txt('Discard slip number')],true),sign]},
{id:'product_lab',name:'Finished Product Sample Analysis',short:'Product laboratory',department:'laboratory',creators:['laboratory'],reviewers:['qc'],page:12,code:'REC/LAB-012',retention:'1 year (source)',description:'Record finished-product microbiological and pH results.',batch:true,sections:[sec('header','Sample details',[txt('Customer'),txt('Sample description',true),txt('Sample type',true),txt('Sample condition'),d('Sample receiving date',true),d('Test start date',true),d('Test completion date',true),txt('Analyzed by',true)]),sec('results','Analysis results',[txt('Test parameter',true),txt('Method'),txt('Approved standard'),txt('Result',true),txt('Unit'),s('Conclusion',pass,true),s('Correction needed',yes,true)],true,['TPC','Coliform','E. coli','S. aureus','Listeria sp.','Salmonella sp.','pH'].map(x=>({test_parameter:x}))),sec('correction','Corrective action',[memo('Recommended corrective action')]),sign]},
{id:'steam',name:'Steam Box Report',short:'Steam box cooking',department:'production',creators:['production','qc'],reviewers:['qc'],page:13,code:'REC/QC-015',retention:'6 months (source)',description:'CCP 1B cycle readings, corrective actions and QC verification.',batch:true,sections:[sec('header','Cooking cycle',[txt('Product name',true),txt('Box number',true),txt('Cycle ID',true),d('Date',true),txt('Batches in cycle',true),n('Product temperature before steam (C)'),n('Input (kg)'),n('Output total (kg)'),n('Rework / regrade (kg)'),t('Showering 1 start'),t('Showering 1 finish'),t('Showering 2 start'),t('Showering 2 finish'),txt('Approved cooking specification')]),sec('readings','Actual monitoring and corrective actions',[txt('Step time'),n('Setting temperature (C)'),n('Setting RH (%)'),t('Actual time'),n('Actual ambient temperature (C)',true),n('Core temperature (C)',true),n('Actual RH (%)'),n('Correction CT1 (C)'),n('Correction CT2 (C)'),n('Correction CT3 (C)'),s('Correction 1 pass',pass),txt('Extended cooking time'),s('Correction 2 pass',pass),memo('Remark')],true),sec('verification','Cycle verification',[s('Cycle result',pass,true),memo('Reheat / corrective action'),txt('QC supervisor')]),sign]},
{id:'post_heat',name:'Cutting, Packing, Drying & Cooling',short:'Post-heat and packing',department:'production',creators:['production','qc'],reviewers:['qc'],page:14,code:'REC/QC-062',retention:'1 year (source)',description:'Track product through drying, cooling, packing and blast freezing.',batch:true,sections:[sec('header','Packing session',[s('Packaging type',['Pack brand','Clear pack','Secondary pack'],true),txt('Balance ID'),txt('Thermometer ID'),d('Production date',true),s('Shift',['Day','Night'],true)]),sec('rows','Process and packing records',[txt('Product name',true),txt('Batch / lot',true),t('Drying start'),t('Drying finish'),n('Before pack core temperature (C)'),t('Cooling start'),t('Cooling finish'),t('Packing time'),n('Pack size (g)',true),d('Sticker manufacturing date'),d('Sticker expiry date'),txt('Sticker batch / lot'),n('Pack core temperature (C)'),txt('Weight range per piece (g)'),n('Average weight of 3 packs (g)'),n('Total packs in batch',true),t('Blast freezing start'),t('Blast freezing finish'),n('Blast freezing core temperature (C)'),n('Handover warehouse core temperature (C)'),txt('QC sign'),memo('Remark')],true),sign]},
{id:'metal',name:'Metal Detector Report',short:'Metal detection',department:'qc',creators:['qc'],reviewers:['qc'],page:15,code:'REC/QC-046',retention:'2 years (source)',description:'CCP 2P detector checks, holds and corrective-action rechecks.',batch:true,sections:[sec('header','Detector session',[s('Shift',['Day','Night'],true),txt('Metal detector number',true),d('Production date',true),txt('Approved test-piece specification')]),sec('rows','Detector checks',[t('Time'),txt('Product name',true),txt('Program number'),txt('Product code'),txt('Lot / batch',true),n('Quantity (packs)'),s('Fe test',pass,true),s('Non-Fe test',pass,true),s('SUS test',pass,true),s('Test arm reject',pass,true),txt('CA1 holding lot'),n('CA1 holding quantity (packs)'),d('CA1 recheck date'),txt('CA2 holding lot'),n('CA2 holding quantity (packs)'),txt('CA2 recheck result'),d('NC record date')],true),sec('verification','Disposition',[s('Overall result',pass,true),memo('Corrective action'),txt('CA1 by'),txt('CA2 by')]),sign]},
{id:'chiller',name:'Temperature Record for Chiller Cabinet',short:'Chiller temperatures',department:'warehouse',creators:['warehouse','qc'],reviewers:['qc'],page:16,code:'REC/QC-031',retention:'6 months (source)',description:'Log room and product temperatures with corrective-action follow-up.',sections:[sec('header','Cabinet details',[txt('Cabinet number',true),txt('Location',true),txt('Approved temperature specification')]),sec('rows','Temperature observations',[d('Date',true),t('Time'),n('Room temperature (C)',true),n('Product core temperature (C)',true),txt('Affected lot / batch'),memo('Corrective action'),txt('Recorded by'),txt('QC supervisor')],true),sign]},
{id:'packing_transfer',name:'Product Packing & Transfer Record',short:'Packing and transfer',department:'production',creators:['production','planning'],reviewers:['qc'],page:17,code:'REC/PD-010',retention:'1 year (source)',description:'Reconcile packaging counts and authorize a warehouse transfer.',batch:true,sections:[sec('header','Transfer details',[txt('Product category'),d('Production date',true)]),sec('rows','Product and sticker reconciliation',[txt('Product code'),txt('Product name',true),txt('Pack size',true),txt('Batch / lot',true),n('Prepared packs',true),s('Price label',yes),n('Free labels'),n('More labels needed'),n('Labels returned'),n('Actual produced packs',true),memo('Remark'),txt('Transferred by PD'),txt('Received by WH')],true),sign]},
{id:'fg_receipt',name:'Finished Goods Warehouse Receipt',short:'FG warehouse receipt',department:'warehouse',creators:['warehouse'],reviewers:['warehouse'],page:18,code:'REC/WH-006',retention:'2 years (source)',description:'Receive a released production batch into finished-goods inventory.',batch:true,effect:'Approval creates FG stock only after required batch checks are approved.',sections:[sec('header','Receipt details',[d('Date',true),txt('Station',true),txt('Storage location',true),txt('Packing transfer record ID',true)]),sec('rows','Finished goods lots',[txt('Product code'),txt('Product name',true),n('Size (g)',true),txt('Lot number',true),n('Quantity (packs)',true),d('Manufacturing date',true),d('Expiry date',true),txt('Delivered by'),txt('QC checked'),txt('WH received'),t('Time'),memo('Remarks')],true),sign]},
{id:'dispatch',name:'Product Delivery Report',short:'Product delivery',department:'dispatch',creators:['dispatch'],reviewers:['qc'],page:19,code:'REC/QC-003',retention:'2 years (source)',description:'Allocate released finished-goods lots to customer deliveries.',batch:false,effect:'Approval deducts shipped stock and links each lot to its customer.',sections:[sec('header','Delivery details',[txt('Van number',true),d('Date',true),txt('Route',true),txt('Driver name',true),t('Preparation start'),t('Preparation finish'),s('Van cleanliness',['Clean with no bad smell','Needs correction'],true),memo('Cleanliness note'),s('Vehicle temperature range',['-20 to -30 C','0 to 4 C','4 to 10 C','Above 10 C'],true),txt('Security seal number'),s('Ice pack as standard',yes,true),memo('Ice note'),s('Delivery staff hygiene',['Good / properly dressed','Needs improvement'],true)]),sec('rows','Customer allocations',[txt('Customer name',true),txt('Inventory lot ID',true),txt('Product name',true),txt('Product size'),txt('Product code'),d('Manufacturing date'),d('Expiry date'),txt('Lot number'),n('Quantity (packs)',true),s('Label / seal check',pass,true),n('Product temperature (C)',true)],true),sign]},
{id:'planning',name:'Production Order',short:'Production planning',department:'planning',creators:['planning'],reviewers:['planning'],page:null,code:'DIG/PLAN-001',retention:'Configure with the factory',description:'Digital extension: schedule an order and create its unique production batch.',effect:'Approval creates a planned production batch.',sections:[sec('header','Production order',[txt('Batch ID',true),txt('Product name',true),txt('Product code'),n('Target quantity (kg)',true),d('Scheduled date',true),s('Shift',['Day','Night'],true),txt('Production line',true),txt('Recipe version'),txt('Order reference'),s('Priority',['Normal','High'],true)]),sec('requirements','Material requirements',[txt('Material',true),n('Required quantity',true),s('Unit',['kg','g','pack','pcs','L'],true)],true),sign]},
{id:'issue',name:'Material Issue to Production',short:'Material issue',department:'warehouse',creators:['warehouse'],reviewers:['warehouse'],page:null,code:'DIG/WH-001',retention:'Configure with the factory',description:'Digital extension: deduct released raw materials and link them to production.',batch:true,effect:'Approval deducts stock and records batch input genealogy.',sections:[sec('header','Issue details',[d('Issue date',true),txt('Issued by'),txt('Received by production')]),sec('rows','Lot allocations',[txt('Inventory lot ID',true),n('Issue quantity',true),s('Unit',['kg','g','pack','pcs','L'],true)],true),sign]}
];
export const formById=Object.fromEntries(forms.map(x=>[x.id,x])) as Record<string,FormDef>;
export const requiredBatchChecks=['grinding','sausage','steam','post_heat','metal','product_lab','packing_transfer'];
export function blankData(def:FormDef):Record<string,any>{return Object.fromEntries(def.sections.map(s=>[s.id,s.repeat?(s.initial?structuredClone(s.initial):[{}]):{}]));}
export const processSteps=[
{number:'01',name:'Receive & inspect',description:'Material, vegetables, flour, premix, casing, packaging and water sources.',forms:['receiving','water_lab']},
{number:'02',name:'Store & prepare',description:'Cold storage, vegetable cleaning, sieving and premix preparation.',forms:['chiller','vegetable','sieving','premix_prep','premix_check']},
{number:'03',name:'Plan & process',description:'Issue released lots, grind meat, mix ingredients and link sausage.',forms:['planning','issue','grinding','sausage']},
{number:'04',name:'Cook & verify',description:'Showering, steam-box cooking, laboratory tests and deviation control.',forms:['steam','product_lab','nc','nc_balance']},
{number:'05',name:'Pack & release',description:'Drying, cooling, peeling/cutting, sealing, metal detection and freezing.',forms:['post_heat','metal','packing_transfer']},
{number:'06',name:'Store & dispatch',description:'Warehouse receipt, storage monitoring and customer delivery.',forms:['fg_receipt','chiller','dispatch']}
];
