import {blankData, forms, formById, requiredBatchChecks, roles, type FormDef, type Role} from './catalog';
export type Status='Draft'|'Submitted'|'Approved'|'Returned'|'Rejected';
export type RecordItem={id:string;form:string;batch:string;status:Status;data:Record<string,any>;createdAt:string;updatedAt:string;createdBy:string;revision:number;supersedes?:string;history:{at:string;by:string;action:string;note:string}[];attachments:{id:string;name:string;type:string;size:number}[]};
export type Lot={id:string;code:string;material:string;type:'Raw material'|'Finished goods';quantity:number;unit:string;mfg:string;expiry:string;location:string;supplier:string;status:'Released'|'Hold'|'Rejected';source:string;batch:string};
export type Batch={id:string;product:string;code:string;target:number;date:string;shift:string;line:string;status:'Planned'|'In progress'|'Released'|'Hold'|'Rejected';inputs:{lot:string;quantity:number;unit:string;record:string}[];parents:string[];order:string};
export type Movement={id:string;at:string;lot:string;delta:number;unit:string;type:string;record:string;batch:string;customer?:string};
export type Audit={id:string;at:string;by:string;action:string;record:string;note:string};
export type Master={id:string;category:string;name:string;code:string;detail:string};
export type State={schemaVersion:number;profile:Role|null;records:RecordItem[];lots:Lot[];batches:Batch[];movements:Movement[];audit:Audit[];masters:Master[];settings:{plant:string;timezone:string;requiredChecks:string[]};seededAt:string};
export const uid=(prefix:string)=>`${prefix}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const now=()=>new Date().toISOString();
export const canCreate=(role:Role|null,def:FormDef)=>role==='admin'||!!role&&def.creators.includes(role);
export const canReview=(role:Role|null,def:FormDef)=>role==='admin'||!!role&&def.reviewers.includes(role);
export const person=(role:Role|null)=>roles.find(x=>x.id===role)?.person||'Demo user';
const num=(v:any)=>{const x=Number(v);if(!Number.isFinite(x))throw Error('Enter a valid numeric quantity.');return x;};
const pos=(v:any)=>{const x=num(v);if(x<=0)throw Error('Quantity must be greater than zero.');return x;};
const round=(v:number)=>Math.round(v*1000000)/1000000;
const requireCondition=(v:any,message:string)=>{if(!v)throw Error(message);};
export function audit(s:State,action:string,record:string,note:string){s.audit.unshift({id:uid('AUD'),at:now(),by:person(s.profile),action,record,note});}
export function effectiveApproved(s:State,r:RecordItem){return r.status==='Approved'&&!s.records.some(x=>x.supersedes===r.id&&x.status==='Approved');}
export function batchBlocked(s:State,id:string,seen=new Set<string>(),allowAuthorizedRework=false):boolean{
if(seen.has(id))return false;seen.add(id);const b=s.batches.find(x=>x.id===id);if(!b)return true;
const activeNC=s.records.filter(r=>r.form==='nc'&&r.batch===id&&(r.status==='Submitted'||effectiveApproved(s,r)));
const explicitHold=activeNC.some(r=>r.status==='Submitted'||r.data.rows.some((x:any)=>['Hold','Scrap / reject'].includes(x.disposition)));
const authorizedRework=allowAuthorizedRework&&activeNC.some(r=>r.status==='Approved'&&r.data.rows.every((x:any)=>['Approved rework','Release after correction'].includes(x.disposition)));
return explicitHold||b.status==='Rejected'||(b.status==='Hold'&&!authorizedRework)||b.inputs.some(i=>s.lots.find(l=>l.id===i.lot)?.status!=='Released')||b.parents.some(p=>batchBlocked(s,p,new Set(seen),true));
}
export function missingChecks(s:State,id:string){return s.settings.requiredChecks.filter(f=>!s.records.some(r=>r.batch===id&&r.form===f&&effectiveApproved(s,r)));}
function validateShape(data:any,def:FormDef){requireCondition(data&&typeof data==='object'&&!Array.isArray(data),'Invalid form data.');const cleaned:Record<string,any>={};for(const section of def.sections){let rows=section.repeat?(Array.isArray(data[section.id])?data[section.id]:[]):[data[section.id]||{}];requireCondition(rows.length<=120,'A section supports up to 120 rows.');rows=rows.map((row:any)=>{requireCondition(row&&typeof row==='object'&&!Array.isArray(row),'Invalid row.');const out:Record<string,string>={};for(const field of section.fields){const v=row[field.key];if(v===undefined||v===null)continue;requireCondition(typeof v==='string'||typeof v==='number','Use text or numbers in fields.');requireCondition(String(v).length<=3000,'A field is too long.');out[field.key]=String(v);}return out;});cleaned[section.id]=section.repeat?rows:rows[0];}return cleaned;}
export function validateRecord(r:RecordItem){const def=formById[r.form];requireCondition(!!def,'Unknown form.');for(const sec of def.sections){const rows=sec.repeat?r.data[sec.id]||[]:[r.data[sec.id]||{}];if(sec.repeat&&sec.fields.some(f=>f.required))requireCondition(rows.length>0,`${sec.title}: add at least one row.`);for(let i=0;i<rows.length;i++){for(const f of sec.fields){const v=rows[i][f.key];if(f.required)requireCondition(v!==undefined&&String(v).trim()!=='',`${sec.title}, row ${i+1}: ${f.label} is required.`);if(v===undefined||v==='')continue;if(f.type==='number')requireCondition(Number.isFinite(Number(v)),`${f.label}: use a valid number.`);if(f.type==='select')requireCondition(f.options?.includes(v),`${f.label}: choose a listed option.`);if(f.type==='date')requireCondition(/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v,`${f.label}: use a valid date.`);if(f.type==='time')requireCondition(/^([01]\d|2[0-3]):[0-5]\d$/.test(v),`${f.label}: use a valid time.`);}}}if(def.batch)requireCondition(r.batch,'Select a production batch.');}
function qualityGate(r:RecordItem){if(r.form==='receiving'){requireCondition(r.data.decision.quality_result==='Pass','QC must record a passing quality result before release.');requireCondition(['None','Conform for use'].includes(r.data.decision.action_required),'Resolve the receiving hold or rejection before approval.');requireCondition(r.data.inspection.every((x:any)=>['Yes','N/A'].includes(x.conforming)),'Every receiving inspection must conform or be marked N/A.');}
if(r.form==='steam')requireCondition(r.data.verification.cycle_result==='Pass','Cooking cycle must pass before approval.');
if(r.form==='metal'){requireCondition(r.data.verification.overall_result==='Pass','Metal detection must pass before approval.');requireCondition(r.data.rows.every((x:any)=>['fe_test','non_fe_test','sus_test','test_arm_reject'].every(k=>x[k]==='Pass')),'All detector test pieces and reject checks must pass.');}
if(['product_lab','water_lab'].includes(r.form)){const rows=r.data[r.form==='product_lab'?'results':'micro'];requireCondition(rows.every((x:any)=>x.conclusion==='Pass'&&x.correction_needed==='No'),'Resolve failed, untested or corrective-action laboratory results before approval.');}
if(r.form==='sieving')requireCondition(r.data.rows.every((x:any)=>x.sieve_condition_before==='Pass'&&x.sieve_condition_after==='Pass'&&x.foreign_material_found==='No'),'Resolve sieve failures and foreign-material findings before approval.');
if(r.form==='premix_check')requireCondition(r.data.rows.every((x:any)=>x.labelling==='Pass'&&x.sealing==='Pass'),'Premix labels and seals must pass.');
if(r.form==='premix_prep')requireCondition(r.data.checks.every((x:any)=>x.preparation_verified==='Pass'),'All premix preparation checks must pass.');
if(r.form==='dispatch'){requireCondition(r.data.header.van_cleanliness==='Clean with no bad smell'&&r.data.header.delivery_staff_hygiene==='Good / properly dressed','Resolve vehicle cleanliness and staff hygiene before dispatch.');requireCondition(r.data.rows.every((x:any)=>x.label_seal_check==='Pass'),'All dispatched product labels and seals must pass.');}}
function movement(s:State,lot:Lot,delta:number,r:RecordItem,type:string,customer?:string){lot.quantity=round(lot.quantity+delta);s.movements.unshift({id:uid('MOV'),at:now(),lot:lot.id,delta,unit:lot.unit,type,record:r.id,batch:r.batch||lot.batch,customer});}
function consume(s:State,r:RecordItem,rows:any[],quantityKey:string,type:'Issue'|'Dispatch'){const allocations=new Map<string,number>();for(const row of rows){const id=row.inventory_lot_id;allocations.set(id,round((allocations.get(id)||0)+pos(row[quantityKey])));}for(const [id,qty]of allocations){const lot=s.lots.find(x=>x.id===id);requireCondition(lot,`Inventory lot ${id} was not found.`);requireCondition(lot!.status==='Released',`Lot ${id} is not released.`);requireCondition(lot!.expiry>=today(),`Lot ${id} has expired.`);requireCondition(qty<=lot!.quantity,`Insufficient stock in ${id}: ${lot!.quantity} ${lot!.unit} available.`);requireCondition(type==='Issue'?lot!.type==='Raw material':lot!.type==='Finished goods',`Select a ${type==='Issue'?'raw material':'finished goods'} lot.`);if(type==='Dispatch')requireCondition(!batchBlocked(s,lot!.batch),`Batch ${lot!.batch} is held or has blocked inputs.`);}
for(const row of rows){const lot=s.lots.find(x=>x.id===row.inventory_lot_id)!;if(type==='Issue')requireCondition(lot.unit===row.unit,'Issue unit must match the lot unit.');const qty=pos(row[quantityKey]);movement(s,lot,-qty,r,type,row.customer_name);if(type==='Issue'){const b=s.batches.find(x=>x.id===r.batch)!;b.inputs.push({lot:lot.id,quantity:qty,unit:lot.unit,record:r.id});b.status='In progress';}}}
function applyApproval(s:State,r:RecordItem){const h=r.data.header||{},rows=r.data.rows||[];
if(r.form==='receiving'){for(const row of r.data.lots){requireCondition(row.expiry_date>=row.manufacturing_date,'Expiry must be on or after manufacturing date.');requireCondition(!s.lots.some(x=>x.type==='Raw material'&&x.material===h.material_name&&x.code===row.lot_number&&x.supplier===h.supplier_source),'This material / supplier lot already exists.');const lot:Lot={id:uid('RM'),code:row.lot_number,material:h.material_name,type:'Raw material',quantity:0,unit:row.unit,mfg:row.manufacturing_date,expiry:row.expiry_date,location:h.storage_location,supplier:h.supplier_source,status:'Released',source:r.id,batch:''};s.lots.push(lot);movement(s,lot,pos(row.quantity),r,'Receipt');}}
if(r.form==='planning'){const id=h.batch_id.trim();requireCondition(!s.batches.some(b=>b.id===id),'Batch ID already exists.');s.batches.push({id,product:h.product_name,code:h.product_code||'',target:pos(h.target_quantity_kg),date:h.scheduled_date,shift:h.shift,line:h.production_line,status:'Planned',inputs:[],parents:[],order:r.id});r.batch=id;}
if(formById[r.form].batch)requireCondition(s.batches.some(b=>b.id===r.batch),'The production batch does not exist.');
if(r.form==='issue'){requireCondition(!s.records.some(x=>x.form==='fg_receipt'&&x.batch===r.batch&&x.status==='Approved'),'This batch already has finished-goods receipts. Create a new batch for additional material.');requireCondition(!batchBlocked(s,r.batch),'Cannot issue to a held or rejected batch.');consume(s,r,rows,'issue_quantity','Issue');}
if(r.form==='fg_receipt'){requireCondition(!batchBlocked(s,r.batch),'Batch or its input materials are on hold.');const missing=missingChecks(s,r.batch);requireCondition(!missing.length,`Complete these batch checks first: ${missing.map(x=>formById[x].short).join(', ')}.`);const transfer=s.records.find(x=>x.id===h.packing_transfer_record_id&&x.form==='packing_transfer'&&x.batch===r.batch&&x.status==='Approved');requireCondition(transfer,'Select an approved packing transfer for this batch.');const priorReceived=s.records.filter(x=>x.id!==r.id&&x.form==='fg_receipt'&&x.status==='Approved'&&x.data.header.packing_transfer_record_id===transfer!.id).flatMap(x=>x.data.rows).reduce((sum:number,x:any)=>sum+num(x.quantity_packs),0);const total=rows.reduce((a:number,x:any)=>a+pos(x.quantity_packs),0),produced=transfer!.data.rows.reduce((a:number,x:any)=>a+num(x.actual_produced_packs),0);requireCondition(total+priorReceived<=produced,'Warehouse receipt exceeds the remaining approved packing-transfer quantity.');for(const row of rows){requireCondition(row.expiry_date>=row.manufacturing_date,'Expiry must be on or after manufacturing date.');requireCondition(!s.lots.some(x=>x.type==='Finished goods'&&x.batch===r.batch&&x.code===row.lot_number),'Finished-goods lot already exists for this batch.');const lot:Lot={id:uid('FG'),code:row.lot_number,material:row.product_name,type:'Finished goods',quantity:0,unit:'pack',mfg:row.manufacturing_date,expiry:row.expiry_date,location:h.storage_location,supplier:'Internal production',status:'Released',source:r.id,batch:r.batch};s.lots.push(lot);movement(s,lot,pos(row.quantity_packs),r,'FG receipt');}s.batches.find(x=>x.id===r.batch)!.status='Released';}
if(r.form==='dispatch')consume(s,r,rows,'quantity_packs','Dispatch');
if(r.form==='nc'){const b=s.batches.find(x=>x.id===r.batch)!;const dispositions=rows.map((x:any)=>x.disposition);b.status=dispositions.includes('Scrap / reject')?'Rejected':dispositions.every((x:string)=>x==='Release after correction')?'In progress':'Hold';for(const lot of s.lots.filter(x=>x.batch===b.id||x.id===h.affected_material_lot))lot.status=b.status==='Rejected'?'Rejected':b.status==='Hold'?'Hold':'Released';}
if(r.form==='nc_balance'){for(const row of rows){const src=s.records.find(x=>x.id===row.approved_nc_record_id&&x.form==='nc'&&x.status==='Approved');requireCondition(src&&src.batch===row.source_batch,'Choose an approved NC record matching the source batch.');requireCondition(row.destination_batch===r.batch,'Destination batch must match the selected batch.');requireCondition(row.source_batch!==r.batch,'A rework source cannot be its own destination.');const dest=s.batches.find(b=>b.id===r.batch)!;const ancestor=(id:string,seen=new Set<string>()):boolean=>{if(id===r.batch)return true;if(seen.has(id))return false;seen.add(id);return !!s.batches.find(b=>b.id===id)?.parents.some(p=>ancestor(p,seen));};requireCondition(!ancestor(row.source_batch),'Rework would create a circular batch relationship.');const eligible=src!.data.rows.filter((x:any)=>x.disposition==='Approved rework').reduce((a:number,x:any)=>a+num(x.affected_quantity_kg),0);const used=s.records.filter(x=>x.form==='nc_balance'&&x.status==='Approved'&&x.id!==r.id).flatMap(x=>x.data.rows).filter((x:any)=>x.approved_nc_record_id===src!.id).reduce((a:number,x:any)=>a+num(x.quantity_used_kg),0);const current=rows.filter((x:any)=>x.approved_nc_record_id===src!.id).reduce((a:number,x:any)=>a+pos(x.quantity_used_kg),0);requireCondition(used+current<=eligible,'Rework quantity exceeds its approved available balance.');if(!dest.parents.includes(row.source_batch))dest.parents.push(row.source_batch);row.available_quantity_kg=String(eligible-used);row.balance_kg=String(round(eligible-used-current));}}
}
export type Command={type:string;[key:string]:any};
export function execute(input:State,cmd:Command):State {const s=structuredClone(input);requireCondition(cmd&&typeof cmd.type==='string','Invalid action.');if(cmd.type==='profile'){requireCondition(roles.some(x=>x.id===cmd.role)||cmd.role===null,'Unknown department profile.');s.profile=cmd.role;audit(s,cmd.role?'Entered department':'Left department','',cmd.role||'');return s;}requireCondition(s.profile,'Choose a department profile first.');
if(cmd.type==='master'){requireCondition(s.profile==='admin','Only the administrator can edit master data.');const row=cmd.entry;requireCondition(row&&['Material','Product','Supplier','Customer','Equipment','Location','Recipe'].includes(row.category),'Choose a master-data category.');requireCondition(typeof row.name==='string'&&row.name.trim().length>0&&row.name.length<=200,'Enter a master-data name.');const entry={id:row.id||uid('MD'),category:row.category,name:row.name.trim(),code:String(row.code||'').slice(0,100),detail:String(row.detail||'').slice(0,1000)};const index=s.masters.findIndex(x=>x.id===entry.id);if(index>=0)s.masters[index]=entry;else s.masters.push(entry);audit(s,'Master data saved',entry.id,entry.name);return s;}
if(cmd.type==='save'){const def=formById[cmd.form];requireCondition(def,'Unknown form.');requireCondition(canCreate(s.profile,def),'This department cannot create or edit this form.');const existing=s.records.find(x=>x.id===cmd.id);if(existing){requireCondition(existing.form===cmd.form,'Form type cannot change.');requireCondition(['Draft','Returned'].includes(existing.status),'Only drafts and returned records can be edited.');}const data=validateShape(cmd.data,def);const batch=String(cmd.batch||'').trim().slice(0,100);if(def.batch)requireCondition(!batch||s.batches.some(b=>b.id===batch),'Select an existing production batch.');const r:RecordItem=existing||{id:uid(def.code.replace(/[^A-Z]/g,'').slice(0,6)),form:def.id,batch,status:'Draft',data,createdAt:now(),updatedAt:now(),createdBy:person(s.profile),revision:0,history:[],attachments:[]};r.data=data;r.batch=batch;r.status='Draft';r.updatedAt=now();r.revision++;r.history.unshift({at:now(),by:person(s.profile),action:'Saved draft',note:String(cmd.note||'').slice(0,1000)});if(!existing)s.records.unshift(r);audit(s,'Saved draft',r.id,def.name);return s;}
const r=s.records.find(x=>x.id===cmd.id);requireCondition(r,'Record not found.');const rec=r!;const def=formById[rec.form];const note=String(cmd.note||'').trim().slice(0,2000);
if(cmd.type==='attachment'){requireCondition(canCreate(s.profile,def)&&['Draft','Returned'].includes(rec.status),'Attachments can only be added to editable records by the owning department.');requireCondition(cmd.attachment&&String(cmd.attachment.id).startsWith('ATT-'),'Invalid attachment.');rec.attachments.push(cmd.attachment);audit(s,'Attachment added',rec.id,cmd.attachment.name);return s;}
if(cmd.type==='submit'){requireCondition(canCreate(s.profile,def),'This department cannot submit this form.');requireCondition(['Draft','Returned'].includes(rec.status),'Only drafts can be submitted.');validateRecord(rec);rec.status='Submitted';if(rec.form==='nc'){const b=s.batches.find(x=>x.id===rec.batch);requireCondition(b,'Select an existing batch.');b!.status='Hold';for(const lot of s.lots.filter(x=>x.batch===rec.batch||x.id===rec.data.header.affected_material_lot))lot.status='Hold';}}
else if(['approve','return','reject'].includes(cmd.type)){requireCondition(canReview(s.profile,def),'This department cannot review this form.');requireCondition(rec.status==='Submitted','Only submitted records can be reviewed.');requireCondition(note,'Enter a review note.');if(cmd.type==='approve'){validateRecord(rec);qualityGate(rec);applyApproval(s,rec);rec.status='Approved';rec.data.sign={...(rec.data.sign||{}),approved_by:person(s.profile)};}else rec.status=cmd.type==='return'?'Returned':'Rejected';}
else if(cmd.type==='revise'){requireCondition(canCreate(s.profile,def),'This department cannot prepare a correction.');requireCondition(['Approved','Rejected'].includes(rec.status),'Only finalized records need a correction copy.');requireCondition(note,'Enter a correction reason.');requireCondition(!['receiving','planning','issue','fg_receipt','dispatch','nc_balance'].includes(rec.form),'Posted stock/order records are locked. Record an NC or a new valid transaction; do not duplicate a posted transaction.');const copy=structuredClone(rec);copy.id=uid('REV');copy.supersedes=rec.id;copy.status='Draft';copy.createdAt=now();copy.updatedAt=now();copy.revision=0;copy.history=[{at:now(),by:person(s.profile),action:'Correction copy',note:`From ${rec.id}: ${note}`}];s.records.unshift(copy);audit(s,'Correction copy created',copy.id,`Original ${rec.id}: ${note}`);return s;}
else throw Error('Unsupported action.');rec.updatedAt=now();rec.history.unshift({at:now(),by:person(s.profile),action:cmd.type,note});audit(s,cmd.type,rec.id,note||def.name);return s;}

function demoRecord(def:FormDef,status:Status,id:string,batch:string):RecordItem{const data=blankData(def);for(const sec of def.sections){const rows=sec.repeat?data[sec.id]:[data[sec.id]];for(const row of rows){for(const f of sec.fields){if(row[f.key]!==undefined)continue;row[f.key]=f.type==='date'?'2026-10-05':f.type==='time'?'09:00':f.type==='number'?'1':f.type==='select'?(f.options!.includes('Pass')?'Pass':f.options!.includes('No')?'No':f.options![0]):f.required?'Demo entry':'';}}}
return{id,form:def.id,batch,status,data,createdAt:'2026-10-05T02:00:00.000Z',updatedAt:'2026-10-05T05:30:00.000Z',createdBy:person(def.department),revision:1,history:[{at:'2026-10-05T05:30:00.000Z',by:'Demo Administrator',action:'Sample record',note:'Synthetic showcase data; not a transcription of factory records.'}],attachments:[]};}
export function seed():State{const batch='DEMO-HSS-1005-01';const s:State={schemaVersion:1,profile:null,records:[],lots:[],batches:[],movements:[],audit:[],masters:[],settings:{plant:'Food Business · Demonstration Plant',timezone:'Asia/Dhaka',requiredChecks:requiredBatchChecks},seededAt:now()};
for(const def of forms){const status:Status=['receiving','vegetable','sieving','premix_check','premix_prep','water_lab','nc','nc_balance','planning'].includes(def.id)?'Draft':'Approved';s.records.push(demoRecord(def,status,`DEMO-${def.id.toUpperCase()}`,def.batch?batch:''));}
const get=(id:string)=>s.records.find(r=>r.form===id)!;
get('receiving').data.header={raw_material_type:'Meat',material_name:'Chicken meat',receiving_date:'2026-10-05',po_number:'DEMO-PO-104',challan_number:'DEMO-CH-104',supplier_source:'Demo Poultry Supplier',qc_inspector:'QC Officer',truck_car_number:'DEMO-VAN-02',sampling_number:'4',storage_location:'Chiller A'};get('receiving').data.lots=[{lot_number:'DEMO-RM-1005-B',manufacturing_date:'2026-10-05',expiry_date:'2026-10-09',quantity:'120',unit:'kg',arrival_temperature_1_c:'3.4',arrival_temperature_2_c:'3.7',arrival_temperature_3_c:'3.5',arrival_temperature_4_c:'3.6'}];get('receiving').data.inspection.forEach((x:any)=>{x.conforming='Yes';x.sample_1='Pass';});get('receiving').data.decision={quantity_check:'On PO required',quality_result:'Pass',action_required:'None'};get('receiving').status='Submitted';
get('planning').data.header={batch_id:'DEMO-HSS-1005-02',product_name:'Chicken Hot Sausage',product_code:'DEMO-HSS',target_quantity_kg:'70',scheduled_date:'2026-10-05',shift:'Day',production_line:'Sausage Line 1',recipe_version:'DEMO-1',priority:'Normal'};get('planning').data.requirements=[{material:'Chicken meat',required_quantity:'30',unit:'kg'},{material:'Chicken skin',required_quantity:'5',unit:'kg'},{material:'Prepared premix',required_quantity:'13.4',unit:'kg'},{material:'Water / ice',required_quantity:'21.6',unit:'kg'}];
const raw=[['RM-DEMO-001','DEMO-MEAT-01','Chicken meat',450,30,'Demo Poultry Supplier'],['RM-DEMO-002','DEMO-SKIN-01','Chicken skin',100,5,'Demo Poultry Supplier'],['RM-DEMO-003','DEMO-PX-01','Prepared premix',60,13.4,'Demo Ingredients Supplier'],['RM-DEMO-004','DEMO-WATER-01','Water / ice',200,21.6,'Demo Utilities']];
const b:Batch={id:batch,product:'Chicken Hot Sausage',code:'DEMO-HSS',target:70,date:'2026-10-05',shift:'Day',line:'Sausage Line 1',status:'Released',inputs:[],parents:[],order:'DEMO-ORDER-001'};s.batches.push(b);
for(const [id,code,material,received,used,supplier]of raw){const lot:Lot={id:String(id),code:String(code),material:String(material),type:'Raw material',quantity:Number(received)-Number(used),unit:'kg',mfg:'2026-10-05',expiry:'2027-10-05',location:'Chiller A',supplier:String(supplier),status:'Released',source:'DEMO-OPENING-STOCK',batch:''};s.lots.push(lot);s.movements.push({id:uid('MOV'),at:'2026-10-05T02:00:00Z',lot:lot.id,delta:Number(received),unit:'kg',type:'Opening stock',record:'DEMO-OPENING-STOCK',batch:''},{id:uid('MOV'),at:'2026-10-05T03:00:00Z',lot:lot.id,delta:-Number(used),unit:'kg',type:'Issue',record:get('issue').id,batch});b.inputs.push({lot:lot.id,quantity:Number(used),unit:'kg',record:get('issue').id});}
get('issue').data.rows=b.inputs.map(x=>({inventory_lot_id:x.lot,issue_quantity:String(x.quantity),unit:x.unit}));
get('sausage').data.header.product_name='Chicken Hot Sausage';get('sausage').data.ingredients=b.inputs.map(x=>({batch_number:batch,start_time:'08:00',finish_time:'08:09',speed:'2',ingredient:s.lots.find(l=>l.id===x.lot)!.material,recipe_quantity_kg:String(x.quantity),actual_quantity_kg:String(x.quantity),source_lot:x.lot,temperature_c:'6.4'}));
get('steam').data.header={product_name:'Chicken Hot Sausage',box_number:'SB-01',cycle_id:'DEMO-CYCLE-01',date:'2026-10-05',batches_in_cycle:batch,input_kg:'70',output_total_kg:'63',approved_cooking_specification:'Demonstration only - validate actual factory specification'};get('steam').data.readings=[{step_time:'01',setting_temperature_c:'55',actual_time:'09:00',actual_ambient_temperature_c:'55',core_temperature_c:'30'},{step_time:'02',setting_temperature_c:'65',actual_time:'09:15',actual_ambient_temperature_c:'65',core_temperature_c:'60'},{step_time:'03',setting_temperature_c:'85',actual_time:'09:25',actual_ambient_temperature_c:'85',core_temperature_c:'80'}];get('steam').data.verification.cycle_result='Pass';
get('metal').data.rows=[{time:'10:30',product_name:'Chicken Hot Sausage',program_number:'DEMO-01',lot_batch:batch,quantity_packs:'63',fe_test:'Pass',non_fe_test:'Pass',sus_test:'Pass',test_arm_reject:'Pass'}];get('metal').data.verification.overall_result='Pass';
get('product_lab').data.header.sample_description='Demo Chicken Hot Sausage';get('product_lab').data.results.forEach((x:any)=>{x.result=x.test_parameter==='pH'?'7.04':'ND';x.conclusion='Pass';x.correction_needed='No';x.approved_standard='Demo - QC verification required';});
get('packing_transfer').data.rows=[{product_code:'DEMO-HSS',product_name:'Chicken Hot Sausage',pack_size:'1000 g',batch_lot:batch,prepared_packs:'63',price_label:'Yes',actual_produced_packs:'63',transferred_by_pd:'Production Operator',received_by_wh:'Warehouse Officer'}];
get('fg_receipt').data.header={date:'2026-10-05',station:'FG',storage_location:'Freezer 1',packing_transfer_record_id:get('packing_transfer').id};get('fg_receipt').data.rows=[{product_code:'DEMO-HSS',product_name:'Chicken Hot Sausage',size_g:'1000',lot_number:'DEMO-FG-01',quantity_packs:'63',manufacturing_date:'2026-10-05',expiry_date:'2027-04-05'}];
s.lots.push({id:'FG-DEMO-001',code:'DEMO-FG-01',material:'Chicken Hot Sausage',type:'Finished goods',quantity:51,unit:'pack',mfg:'2026-10-05',expiry:'2027-04-05',location:'Freezer 1',supplier:'Internal production',status:'Released',source:get('fg_receipt').id,batch});
get('dispatch').data.header={van_number:'DEMO-VAN-01',date:'2026-10-05',route:'Dhaka demo route',driver_name:'Demo Driver',preparation_start:'10:00',preparation_finish:'10:30',van_cleanliness:'Clean with no bad smell',vehicle_temperature_range:'-20 to -30 C',ice_pack_as_standard:'Yes',delivery_staff_hygiene:'Good / properly dressed'};get('dispatch').data.rows=[{customer_name:'Demo Customer A',inventory_lot_id:'FG-DEMO-001',product_name:'Chicken Hot Sausage',product_size:'1000 g',product_code:'DEMO-HSS',manufacturing_date:'2026-10-05',expiry_date:'2027-04-05',lot_number:'DEMO-FG-01',quantity_packs:'12',label_seal_check:'Pass',product_temperature_c:'-18'}];
s.movements.push({id:uid('MOV'),at:'2026-10-05T04:00:00Z',lot:'FG-DEMO-001',delta:63,unit:'pack',type:'FG receipt',record:get('fg_receipt').id,batch},{id:uid('MOV'),at:'2026-10-05T05:00:00Z',lot:'FG-DEMO-001',delta:-12,unit:'pack',type:'Dispatch',record:get('dispatch').id,batch,customer:'Demo Customer A'});
get('nc').data.header={product_name:'Chicken Hot Sausage',report_date:'2026-10-05',location:'Linking area',stage:'Work in process',occurrence:'During preparation',qc_operator:'QC Officer'};get('nc').data.rows=[{nc_characteristic:'Demonstration of a linking defect',affected_quantity_kg:'2',disposition:'Hold',correction_method:'Enter QC-authorized action'}];get('nc_balance').data.rows=[{approved_nc_record_id:'',source_batch:'',nc_product_name:'Chicken Hot Sausage',quantity_used_kg:'1',destination_product:'Chicken Hot Sausage',destination_batch:batch}];
const masters=[['Product','Chicken Hot Sausage','DEMO-HSS','Sausage Line 1'],['Material','Chicken meat','DEMO-MEAT','kg'],['Material','Chicken skin','DEMO-SKIN','kg'],['Material','Prepared premix','DEMO-PX','kg'],['Material','Water / ice','DEMO-WATER','kg'],['Supplier','Demo Poultry Supplier','SUP-01','Sample supplier'],['Customer','Demo Customer A','CUS-01','Dhaka'],['Equipment','Steam Box 1','SB-01','Cooking'],['Equipment','Metal Detector 1','MD-01','Packing'],['Location','Chiller A','CH-01','Raw material'],['Location','Freezer 1','FR-01','Finished goods'],['Recipe','Demo sausage recipe','DEMO-1','Sample formulation - factory validation required']];s.masters=masters.map(([category,name,code,detail])=>({id:uid('MD'),category,name,code,detail}));
s.audit=s.records.filter(r=>r.status==='Approved').slice(0,8).map(r=>({id:uid('AUD'),at:r.updatedAt,by:'Demo Administrator',action:'Sample approved record',record:r.id,note:formById[r.form].name}));return s;}
