// Generated by npm run build:backend. Paste this ENTIRE file into the Supabase dashboard editor.
export const roles = [
    { id: 'admin', name: 'Administrator', person: 'Demo Administrator', description: 'All departments, master data and workflow controls' },
    { id: 'receiving', name: 'Receiving', person: 'Receiving Officer', description: 'Incoming materials, supplier lots and inspection requests' },
    { id: 'warehouse', name: 'Warehouse', person: 'Warehouse Officer', description: 'Stock, material issues, cold rooms and FG receipts' },
    { id: 'planning', name: 'Planning', person: 'Planning Officer', description: 'Production orders, batch targets and requirements' },
    { id: 'production', name: 'Production', person: 'Production Operator', description: 'Preparation, processing, cooking and packing' },
    { id: 'qc', name: 'Quality Control', person: 'QC Manager', description: 'Inspection, release, holds and corrective actions' },
    { id: 'laboratory', name: 'Laboratory', person: 'Laboratory Analyst', description: 'Water, swab and finished-product testing' },
    { id: 'dispatch', name: 'Dispatch', person: 'Dispatch Officer', description: 'Vehicle checks, customer deliveries and lot allocation' },
    { id: 'management', name: 'Management', person: 'Factory Manager', description: 'Read-only oversight, traceability and reports' }
];
const key = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
export function f(label, type = 'text', options, required = false) { return { key: key(label), label, type, options, required }; }
const n = (s, req = false) => f(s, 'number', undefined, req), d = (s, req = false) => f(s, 'date', undefined, req), t = (s) => f(s, 'time'), s = (label, values, req = false) => f(label, 'select', values, req), txt = (label, req = false) => f(label, 'text', undefined, req), memo = (label) => f(label, 'textarea');
const yes = ['Yes', 'No', 'N/A'], pass = ['Pass', 'Not pass', 'Not tested', 'N/A'];
const sec = (id, title, fields, repeat = false, initial) => ({ id, title, fields, repeat, initial });
const sign = sec('sign', 'Review and remarks', [memo('Remarks'), txt('Recorded by'), txt('Checked by'), txt('Reviewed by'), txt('Approved by')]);
const inspection = ['General / Size', 'Color', 'Smell / Weight', 'Cleanliness / Plastic type', 'Other / Sizing / Seal', 'Biological', 'Chemical', 'Physical', 'Product ID / Color printing', 'Packaging', 'Delivery'];
export const forms = [
    { id: 'receiving', name: 'Material Receiving Report', short: 'Material receiving', department: 'receiving', creators: ['receiving', 'qc'], reviewers: ['qc'], page: 2, code: 'REC/QC-004', retention: '2 years (source)', description: 'Record deliveries and lot-level inspection before material release.', effect: 'Approval adds each material lot to released inventory.', sections: [
            sec('header', 'Delivery details', [s('Raw material type', ['Meat', 'Non-Meat', 'Packaging', 'Chemical', 'Others'], true), txt('Material name', true), txt('Specification number'), d('Receiving date', true), txt('PO number'), txt('Challan number'), txt('Receiving number'), txt('Supplier / source', true), txt('QC inspector'), txt('Truck / car number'), txt('Sampling number'), txt('Storage location', true)]),
            sec('lots', 'Material lots', [txt('Lot number', true), d('Manufacturing date', true), d('Expiry date', true), n('Quantity', true), s('Unit', ['kg', 'g', 'pack', 'pcs', 'L'], true), n('Arrival temperature 1 (C)'), n('Arrival temperature 2 (C)'), n('Arrival temperature 3 (C)'), n('Arrival temperature 4 (C)')], true),
            sec('inspection', 'Inspection results', [txt('Criterion', true), txt('Standard / specification'), ...Array.from({ length: 13 }, (_, i) => txt(`Sample ${i + 1}`)), s('Conforming', yes, true)], true, inspection.map(x => ({ criterion: x, standard_specification: 'As approved specification' }))),
            sec('decision', 'Disposition', [s('Quantity check', ['On PO required', 'Less than actual', 'Other'], true), n('Actual quantity'), s('Quality result', pass, true), memo('Recommendation'), txt('NC lot number'), n('NC quantity'), memo('NC characteristic'), s('Action required', ['None', 'Hold with card', 'Rejected', 'Conform for use'], true), txt('Hold card number'), memo('Results after action'), txt('Reported by')]), sign
        ] },
    { id: 'vegetable', name: 'Fresh Vegetable Cleaning Record', short: 'Vegetable cleaning', department: 'production', creators: ['production', 'qc'], reviewers: ['qc'], page: 3, code: 'REC/QC-037', retention: '6 months (source)', description: 'Record washing, solution preparation and cleaning checks.', batch: true, sections: [sec('header', 'Cleaning session', [d('Date', true)]), sec('rows', 'Vegetable cleaning entries', [d('Receiving date', true), txt('Vegetable type', true), txt('Source lot'), s('First rinse with water', yes, true), n('Water (L)'), n('NaHCO3 (g)'), txt('NaHCO3 PDD code'), txt('Solution checked by'), ...Array.from({ length: 6 }, (_, i) => txt(`Dipping observation ${i + 1}`)), memo('Deviation note'), s('Second rinse with water', yes, true), d('Label PDD'), txt('Best before'), memo('Remark')], true), sign] },
    { id: 'sieving', name: 'Sieving Report', short: 'Sieving', department: 'production', creators: ['production'], reviewers: ['production', 'qc'], page: 4, code: 'REC/PX-008', retention: '6 months (source)', description: 'Capture material weight, sieve checks and foreign-material findings.', batch: true, sections: [sec('header', 'Preparation details', [d('Date', true), txt('Scale code'), s('Location', ['Premix preparation', 'Flour preparation', 'Test room', 'Other'], true)]), sec('rows', 'Sieving entries', [txt('Product code'), txt('Product / raw material', true), d('PDD'), txt('Source lot', true), n('Weight before sieving (g)', true), n('Weight after sieving (g)', true), s('Sieve condition before', pass, true), s('Sieve condition after', pass, true), memo('Corrective action'), s('Foreign material found', yes, true), memo('Foreign material details'), memo('Remarks')], true), sign] },
    { id: 'premix_check', name: 'Premix Checking Report', short: 'Premix checking', department: 'production', creators: ['production'], reviewers: ['production', 'qc'], page: 5, code: 'REC/PX-009', retention: '6 months (source)', description: 'Verify premix pack weights, labels and seals.', batch: true, sections: [sec('header', 'Check details', [d('Date', true), txt('Balance code')]), sec('rows', 'Premix observations', [txt('Production code / name', true), txt('Premix number', true), n('Standard weight (g)', true), n('Total packs produced', true), s('Labelling', pass, true), ...Array.from({ length: 5 }, (_, i) => n(`Weight observation ${i + 1} (g)`)), s('Sealing', pass, true), txt('Lot / batch number', true)], true), sign] },
    { id: 'premix_prep', name: 'Premix Preparation Monitoring Form', short: 'Premix preparation', department: 'production', creators: ['production'], reviewers: ['production'], page: 6, code: 'REC/PX-002', retention: '6 months (source)', description: 'Versioned recipe ingredients and preparation checks for each premix batch.', batch: true, sections: [sec('header', 'Preparation details', [txt('Product name', true), txt('Product code'), n('Recipe batch size (kg)', true), n('Number of sets', true), d('Date', true), t('Time'), txt('Recipe version')]), sec('ingredients', 'Ingredients and target quantities', [txt('Premix code', true), txt('Ingredient name', true), n('Target weight (g)', true), txt('Ingredient lot'), d('Ingredient expiry'), memo('Remark')], true), sec('checks', 'Batch preparation checks', [txt('Premix code', true), txt('Ingredient name', true), txt('Prepared batch number', true), n('Actual weight (g)', true), s('Preparation verified', pass, true), txt('Checked by')], true), sign] },
    { id: 'water_lab', name: 'Water & Swab Testing Report', short: 'Water / swab testing', department: 'laboratory', creators: ['laboratory'], reviewers: ['qc'], page: 7, code: 'REC/LAB-005', retention: '1 year (source)', description: 'Microbial and chemical results for water, staff or equipment samples.', sections: [sec('header', 'Sample information', [s('Sample from', ['Machine / Equipment SWAB', 'Staff SWAB', 'Water', 'Other'], true), txt('Other source'), d('Sample receiving date', true), d('Sample collection date', true), txt('Collected by'), txt('Analyzed by', true), d('Analysis date', true)]), sec('micro', 'Microbial test results', [txt('Sample number', true), txt('Source / product name', true), txt('Unit (CFU per cm2 or ml)'), txt('TPC'), txt('Coliform'), txt('E. coli'), txt('S. aureus'), txt('Listeria sp.'), txt('Approved standard reference'), s('Conclusion', pass, true), s('Correction needed', yes, true)], true), sec('chemical', 'Chemical test results', [txt('Sample number'), txt('Source name'), txt('Hardness standard (ppm)'), txt('Hardness actual (ppm)'), txt('DO standard (ppm)'), txt('DO actual (ppm)'), txt('pH standard'), txt('pH actual'), txt('TDS standard (ppm)'), txt('TDS actual (ppm)'), txt('Other parameter'), txt('Other standard'), txt('Other actual')], true), sec('correction', 'Corrective action', [memo('Recommended corrective action')]), sign] },
    { id: 'grinding', name: 'Production Report: Meat Grinding', short: 'Meat grinding', department: 'production', creators: ['production', 'qc'], reviewers: ['qc'], page: 8, code: 'REC/QC-035', retention: '1 year (source)', description: 'Track input meat, grinding settings and measured temperatures.', batch: true, sections: [sec('header', 'Production details', [d('Production date', true), s('Shift', ['Day', 'Night'], true)]), sec('rows', 'Grinding entries', [t('Start time'), d('Debone meat date'), txt('Use for'), txt('Source lot', true), n('Meat input (kg)', true), n('Plate diameter (mm)'), n('Temperature after grinding (C)', true), txt('Grinding meat code'), txt('QC sign'), memo('Remark')], true), sign] },
    { id: 'nc_balance', name: 'NC Use & Balance Record', short: 'NC use and balance', department: 'qc', creators: ['qc', 'production'], reviewers: ['qc'], page: 9, code: 'REC/QC-014', retention: '3 months (source)', description: 'Track authorized rework quantities and the destination batch.', batch: true, effect: 'Links source and destination batches; rejects overuse of approved rework.', sections: [sec('header', 'Record details', [d('Date', true)]), sec('rows', 'Rework consumption', [t('Time'), txt('Approved NC record ID', true), txt('Source batch', true), txt('NC product code'), txt('NC product name', true), d('NC production date'), n('Available quantity (kg)'), n('Quantity used (kg)', true), txt('Destination product', true), d('Destination production date'), txt('Destination batch', true), n('Balance (kg)'), txt('Recorded by')], true), sign] },
    { id: 'sausage', name: 'Sausage Mixing & Linking Inspection', short: 'Mixing and linking', department: 'production', creators: ['production', 'qc'], reviewers: ['qc'], page: 10, code: 'REC/QC-051', retention: '1 year (source)', description: 'Capture formulation inputs, silent-cutter settings and linking checks.', batch: true, sections: [sec('header', 'Production details', [txt('Product name', true), txt('Thermometer ID'), txt('Balance ID'), d('Production date', true), s('Shift', ['Day', 'Night'], true)]), sec('ingredients', 'Silent cutter / ingredient inputs', [txt('Batch number', true), t('Start time'), t('Finish time'), n('Speed'), txt('Ingredient', true), n('Recipe quantity (kg)'), n('Actual quantity (kg)', true), txt('Source lot', true), d('DD / actual date'), n('Temperature (C)')], true), sec('linking', 'Auto-linking and dimensional checks', [txt('Batch number', true), t('Start time'), t('Finish time'), txt('Casing code'), txt('Horn number'), n('Length (cm)'), n('Diameter (mm)'), n('Weight (g)'), txt('Approved size specification'), memo('Remarks')], true), sign] },
    { id: 'nc', name: 'Nonconforming Product Report', short: 'Nonconforming product', department: 'qc', creators: ['qc', 'production', 'warehouse'], reviewers: ['qc'], page: 11, code: 'REC/QC-021', retention: '1 year (source)', description: 'Hold affected batches and record an authorized disposition.', batch: true, effect: 'Submitting places the batch on hold. QC disposition controls release, rework or rejection.', sections: [sec('header', 'Nonconformance details', [txt('Product name', true), txt('Product code'), d('Report date', true), t('Time'), txt('Location'), s('Stage', ['Raw material', 'Work in process', 'Finished goods', 'Return'], true), s('Occurrence', ['During storage', 'During preparation', 'Other'], true), d('Production date'), d('Return date'), txt('Affected material lot'), txt('QC operator')]), sec('rows', 'Corrective action', [memo('NC characteristic'), n('Affected quantity (kg)', true), s('Disposition', ['Hold', 'Release after correction', 'Approved rework', 'Scrap / reject'], true), memo('Correction method'), txt('Rework product'), txt('Destination batch'), d('Correction finished on'), txt('Discard slip number')], true), sign] },
    { id: 'product_lab', name: 'Finished Product Sample Analysis', short: 'Product laboratory', department: 'laboratory', creators: ['laboratory'], reviewers: ['qc'], page: 12, code: 'REC/LAB-012', retention: '1 year (source)', description: 'Record finished-product microbiological and pH results.', batch: true, sections: [sec('header', 'Sample details', [txt('Customer'), txt('Sample description', true), txt('Sample type', true), txt('Sample condition'), d('Sample receiving date', true), d('Test start date', true), d('Test completion date', true), txt('Analyzed by', true)]), sec('results', 'Analysis results', [txt('Test parameter', true), txt('Method'), txt('Approved standard'), txt('Result', true), txt('Unit'), s('Conclusion', pass, true), s('Correction needed', yes, true)], true, ['TPC', 'Coliform', 'E. coli', 'S. aureus', 'Listeria sp.', 'Salmonella sp.', 'pH'].map(x => ({ test_parameter: x }))), sec('correction', 'Corrective action', [memo('Recommended corrective action')]), sign] },
    { id: 'steam', name: 'Steam Box Report', short: 'Steam box cooking', department: 'production', creators: ['production', 'qc'], reviewers: ['qc'], page: 13, code: 'REC/QC-015', retention: '6 months (source)', description: 'CCP 1B cycle readings, corrective actions and QC verification.', batch: true, sections: [sec('header', 'Cooking cycle', [txt('Product name', true), txt('Box number', true), txt('Cycle ID', true), d('Date', true), txt('Batches in cycle', true), n('Product temperature before steam (C)'), n('Input (kg)'), n('Output total (kg)'), n('Rework / regrade (kg)'), t('Showering 1 start'), t('Showering 1 finish'), t('Showering 2 start'), t('Showering 2 finish'), txt('Approved cooking specification')]), sec('readings', 'Actual monitoring and corrective actions', [txt('Step time'), n('Setting temperature (C)'), n('Setting RH (%)'), t('Actual time'), n('Actual ambient temperature (C)', true), n('Core temperature (C)', true), n('Actual RH (%)'), n('Correction CT1 (C)'), n('Correction CT2 (C)'), n('Correction CT3 (C)'), s('Correction 1 pass', pass), txt('Extended cooking time'), s('Correction 2 pass', pass), memo('Remark')], true), sec('verification', 'Cycle verification', [s('Cycle result', pass, true), memo('Reheat / corrective action'), txt('QC supervisor')]), sign] },
    { id: 'post_heat', name: 'Cutting, Packing, Drying & Cooling', short: 'Post-heat and packing', department: 'production', creators: ['production', 'qc'], reviewers: ['qc'], page: 14, code: 'REC/QC-062', retention: '1 year (source)', description: 'Track product through drying, cooling, packing and blast freezing.', batch: true, sections: [sec('header', 'Packing session', [s('Packaging type', ['Pack brand', 'Clear pack', 'Secondary pack'], true), txt('Balance ID'), txt('Thermometer ID'), d('Production date', true), s('Shift', ['Day', 'Night'], true)]), sec('rows', 'Process and packing records', [txt('Product name', true), txt('Batch / lot', true), t('Drying start'), t('Drying finish'), n('Before pack core temperature (C)'), t('Cooling start'), t('Cooling finish'), t('Packing time'), n('Pack size (g)', true), d('Sticker manufacturing date'), d('Sticker expiry date'), txt('Sticker batch / lot'), n('Pack core temperature (C)'), txt('Weight range per piece (g)'), n('Average weight of 3 packs (g)'), n('Total packs in batch', true), t('Blast freezing start'), t('Blast freezing finish'), n('Blast freezing core temperature (C)'), n('Handover warehouse core temperature (C)'), txt('QC sign'), memo('Remark')], true), sign] },
    { id: 'metal', name: 'Metal Detector Report', short: 'Metal detection', department: 'qc', creators: ['qc'], reviewers: ['qc'], page: 15, code: 'REC/QC-046', retention: '2 years (source)', description: 'CCP 2P detector checks, holds and corrective-action rechecks.', batch: true, sections: [sec('header', 'Detector session', [s('Shift', ['Day', 'Night'], true), txt('Metal detector number', true), d('Production date', true), txt('Approved test-piece specification')]), sec('rows', 'Detector checks', [t('Time'), txt('Product name', true), txt('Program number'), txt('Product code'), txt('Lot / batch', true), n('Quantity (packs)'), s('Fe test', pass, true), s('Non-Fe test', pass, true), s('SUS test', pass, true), s('Test arm reject', pass, true), txt('CA1 holding lot'), n('CA1 holding quantity (packs)'), d('CA1 recheck date'), txt('CA2 holding lot'), n('CA2 holding quantity (packs)'), txt('CA2 recheck result'), d('NC record date')], true), sec('verification', 'Disposition', [s('Overall result', pass, true), memo('Corrective action'), txt('CA1 by'), txt('CA2 by')]), sign] },
    { id: 'chiller', name: 'Temperature Record for Chiller Cabinet', short: 'Chiller temperatures', department: 'warehouse', creators: ['warehouse', 'qc'], reviewers: ['qc'], page: 16, code: 'REC/QC-031', retention: '6 months (source)', description: 'Log room and product temperatures with corrective-action follow-up.', sections: [sec('header', 'Cabinet details', [txt('Cabinet number', true), txt('Location', true), txt('Approved temperature specification')]), sec('rows', 'Temperature observations', [d('Date', true), t('Time'), n('Room temperature (C)', true), n('Product core temperature (C)', true), txt('Affected lot / batch'), memo('Corrective action'), txt('Recorded by'), txt('QC supervisor')], true), sign] },
    { id: 'packing_transfer', name: 'Product Packing & Transfer Record', short: 'Packing and transfer', department: 'production', creators: ['production', 'planning'], reviewers: ['qc'], page: 17, code: 'REC/PD-010', retention: '1 year (source)', description: 'Reconcile packaging counts and authorize a warehouse transfer.', batch: true, sections: [sec('header', 'Transfer details', [txt('Product category'), d('Production date', true)]), sec('rows', 'Product and sticker reconciliation', [txt('Product code'), txt('Product name', true), txt('Pack size', true), txt('Batch / lot', true), n('Prepared packs', true), s('Price label', yes), n('Free labels'), n('More labels needed'), n('Labels returned'), n('Actual produced packs', true), memo('Remark'), txt('Transferred by PD'), txt('Received by WH')], true), sign] },
    { id: 'fg_receipt', name: 'Finished Goods Warehouse Receipt', short: 'FG warehouse receipt', department: 'warehouse', creators: ['warehouse'], reviewers: ['warehouse'], page: 18, code: 'REC/WH-006', retention: '2 years (source)', description: 'Receive a released production batch into finished-goods inventory.', batch: true, effect: 'Approval creates FG stock only after required batch checks are approved.', sections: [sec('header', 'Receipt details', [d('Date', true), txt('Station', true), txt('Storage location', true), txt('Packing transfer record ID', true)]), sec('rows', 'Finished goods lots', [txt('Product code'), txt('Product name', true), n('Size (g)', true), txt('Lot number', true), n('Quantity (packs)', true), d('Manufacturing date', true), d('Expiry date', true), txt('Delivered by'), txt('QC checked'), txt('WH received'), t('Time'), memo('Remarks')], true), sign] },
    { id: 'dispatch', name: 'Product Delivery Report', short: 'Product delivery', department: 'dispatch', creators: ['dispatch'], reviewers: ['qc'], page: 19, code: 'REC/QC-003', retention: '2 years (source)', description: 'Allocate released finished-goods lots to customer deliveries.', batch: false, effect: 'Approval deducts shipped stock and links each lot to its customer.', sections: [sec('header', 'Delivery details', [txt('Van number', true), d('Date', true), txt('Route', true), txt('Driver name', true), t('Preparation start'), t('Preparation finish'), s('Van cleanliness', ['Clean with no bad smell', 'Needs correction'], true), memo('Cleanliness note'), s('Vehicle temperature range', ['-20 to -30 C', '0 to 4 C', '4 to 10 C', 'Above 10 C'], true), txt('Security seal number'), s('Ice pack as standard', yes, true), memo('Ice note'), s('Delivery staff hygiene', ['Good / properly dressed', 'Needs improvement'], true)]), sec('rows', 'Customer allocations', [txt('Customer name', true), txt('Inventory lot ID', true), txt('Product name', true), txt('Product size'), txt('Product code'), d('Manufacturing date'), d('Expiry date'), txt('Lot number'), n('Quantity (packs)', true), s('Label / seal check', pass, true), n('Product temperature (C)', true)], true), sign] },
    { id: 'planning', name: 'Production Order', short: 'Production planning', department: 'planning', creators: ['planning'], reviewers: ['planning'], page: null, code: 'DIG/PLAN-001', retention: 'Configure with the factory', description: 'Digital extension: schedule an order and create its unique production batch.', effect: 'Approval creates a planned production batch.', sections: [sec('header', 'Production order', [txt('Batch ID', true), txt('Product name', true), txt('Product code'), n('Target quantity (kg)', true), d('Scheduled date', true), s('Shift', ['Day', 'Night'], true), txt('Production line', true), txt('Recipe version'), txt('Order reference'), s('Priority', ['Normal', 'High'], true)]), sec('requirements', 'Material requirements', [txt('Material', true), n('Required quantity', true), s('Unit', ['kg', 'g', 'pack', 'pcs', 'L'], true)], true), sign] },
    { id: 'issue', name: 'Material Issue to Production', short: 'Material issue', department: 'warehouse', creators: ['warehouse'], reviewers: ['warehouse'], page: null, code: 'DIG/WH-001', retention: 'Configure with the factory', description: 'Digital extension: deduct released raw materials and link them to production.', batch: true, effect: 'Approval deducts stock and records batch input genealogy.', sections: [sec('header', 'Issue details', [d('Issue date', true), txt('Issued by'), txt('Received by production')]), sec('rows', 'Lot allocations', [txt('Inventory lot ID', true), n('Issue quantity', true), s('Unit', ['kg', 'g', 'pack', 'pcs', 'L'], true)], true), sign] }
];
export const formById = Object.fromEntries(forms.map(x => [x.id, x]));
export const requiredBatchChecks = ['grinding', 'sausage', 'steam', 'post_heat', 'metal', 'product_lab', 'packing_transfer'];
export function blankData(def) { return Object.fromEntries(def.sections.map(s => [s.id, s.repeat ? (s.initial ? structuredClone(s.initial) : [{}]) : {}])); }
export const processSteps = [
    { number: '01', name: 'Receive & inspect', description: 'Material, vegetables, flour, premix, casing, packaging and water sources.', forms: ['receiving', 'water_lab'] },
    { number: '02', name: 'Store & prepare', description: 'Cold storage, vegetable cleaning, sieving and premix preparation.', forms: ['chiller', 'vegetable', 'sieving', 'premix_prep', 'premix_check'] },
    { number: '03', name: 'Plan & process', description: 'Issue released lots, grind meat, mix ingredients and link sausage.', forms: ['planning', 'issue', 'grinding', 'sausage'] },
    { number: '04', name: 'Cook & verify', description: 'Showering, steam-box cooking, laboratory tests and deviation control.', forms: ['steam', 'product_lab', 'nc', 'nc_balance'] },
    { number: '05', name: 'Pack & release', description: 'Drying, cooling, peeling/cutting, sealing, metal detection and freezing.', forms: ['post_heat', 'metal', 'packing_transfer'] },
    { number: '06', name: 'Store & dispatch', description: 'Warehouse receipt, storage monitoring and customer delivery.', forms: ['fg_receipt', 'chiller', 'dispatch'] }
];
export const uid = (prefix) => `${prefix}-${crypto.randomUUID().slice(0, 8).toUpperCase()}`;
export const today = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Dhaka', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
export const now = () => new Date().toISOString();
export const canCreate = (role, def) => role === 'admin' || !!role && def.creators.includes(role);
export const canReview = (role, def) => role === 'admin' || !!role && def.reviewers.includes(role);
export const person = (role) => roles.find(x => x.id === role)?.person || 'Demo user';
const num = (v) => { const x = Number(v); if (!Number.isFinite(x))
    throw Error('Enter a valid numeric quantity.'); return x; };
const pos = (v) => { const x = num(v); if (x <= 0)
    throw Error('Quantity must be greater than zero.'); return x; };
const round = (v) => Math.round(v * 1000000) / 1000000;
const requireCondition = (v, message) => { if (!v)
    throw Error(message); };
export function audit(s, action, record, note) { s.audit.unshift({ id: uid('AUD'), at: now(), by: person(s.profile), action, record, note }); }
export function effectiveApproved(s, r) { return r.status === 'Approved' && !s.records.some(x => x.supersedes === r.id && x.status === 'Approved'); }
export function batchBlocked(s, id, seen = new Set(), allowAuthorizedRework = false) {
    if (seen.has(id))
        return false;
    seen.add(id);
    const b = s.batches.find(x => x.id === id);
    if (!b)
        return true;
    const activeNC = s.records.filter(r => r.form === 'nc' && r.batch === id && (r.status === 'Submitted' || effectiveApproved(s, r)));
    const explicitHold = activeNC.some(r => r.status === 'Submitted' || r.data.rows.some((x) => ['Hold', 'Scrap / reject'].includes(x.disposition)));
    const authorizedRework = allowAuthorizedRework && activeNC.some(r => r.status === 'Approved' && r.data.rows.every((x) => ['Approved rework', 'Release after correction'].includes(x.disposition)));
    return explicitHold || b.status === 'Rejected' || (b.status === 'Hold' && !authorizedRework) || b.inputs.some(i => s.lots.find(l => l.id === i.lot)?.status !== 'Released') || b.parents.some(p => batchBlocked(s, p, new Set(seen), true));
}
export function missingChecks(s, id) { return s.settings.requiredChecks.filter(f => !s.records.some(r => r.batch === id && r.form === f && effectiveApproved(s, r))); }
function validateShape(data, def) { requireCondition(data && typeof data === 'object' && !Array.isArray(data), 'Invalid form data.'); const cleaned = {}; for (const section of def.sections) {
    let rows = section.repeat ? (Array.isArray(data[section.id]) ? data[section.id] : []) : [data[section.id] || {}];
    requireCondition(rows.length <= 120, 'A section supports up to 120 rows.');
    rows = rows.map((row) => { requireCondition(row && typeof row === 'object' && !Array.isArray(row), 'Invalid row.'); const out = {}; for (const field of section.fields) {
        const v = row[field.key];
        if (v === undefined || v === null)
            continue;
        requireCondition(typeof v === 'string' || typeof v === 'number', 'Use text or numbers in fields.');
        requireCondition(String(v).length <= 3000, 'A field is too long.');
        out[field.key] = String(v);
    } return out; });
    cleaned[section.id] = section.repeat ? rows : rows[0];
} return cleaned; }
export function validateRecord(r) { const def = formById[r.form]; requireCondition(!!def, 'Unknown form.'); for (const sec of def.sections) {
    const rows = sec.repeat ? r.data[sec.id] || [] : [r.data[sec.id] || {}];
    if (sec.repeat && sec.fields.some(f => f.required))
        requireCondition(rows.length > 0, `${sec.title}: add at least one row.`);
    for (let i = 0; i < rows.length; i++) {
        for (const f of sec.fields) {
            const v = rows[i][f.key];
            if (f.required)
                requireCondition(v !== undefined && String(v).trim() !== '', `${sec.title}, row ${i + 1}: ${f.label} is required.`);
            if (v === undefined || v === '')
                continue;
            if (f.type === 'number')
                requireCondition(Number.isFinite(Number(v)), `${f.label}: use a valid number.`);
            if (f.type === 'select')
                requireCondition(f.options?.includes(v), `${f.label}: choose a listed option.`);
            if (f.type === 'date')
                requireCondition(/^\d{4}-\d{2}-\d{2}$/.test(v) && !isNaN(Date.parse(v)) && new Date(v).toISOString().slice(0, 10) === v, `${f.label}: use a valid date.`);
            if (f.type === 'time')
                requireCondition(/^([01]\d|2[0-3]):[0-5]\d$/.test(v), `${f.label}: use a valid time.`);
        }
    }
} if (def.batch)
    requireCondition(r.batch, 'Select a production batch.'); }
function qualityGate(r) {
    if (r.form === 'receiving') {
        requireCondition(r.data.decision.quality_result === 'Pass', 'QC must record a passing quality result before release.');
        requireCondition(['None', 'Conform for use'].includes(r.data.decision.action_required), 'Resolve the receiving hold or rejection before approval.');
        requireCondition(r.data.inspection.every((x) => ['Yes', 'N/A'].includes(x.conforming)), 'Every receiving inspection must conform or be marked N/A.');
    }
    if (r.form === 'steam')
        requireCondition(r.data.verification.cycle_result === 'Pass', 'Cooking cycle must pass before approval.');
    if (r.form === 'metal') {
        requireCondition(r.data.verification.overall_result === 'Pass', 'Metal detection must pass before approval.');
        requireCondition(r.data.rows.every((x) => ['fe_test', 'non_fe_test', 'sus_test', 'test_arm_reject'].every(k => x[k] === 'Pass')), 'All detector test pieces and reject checks must pass.');
    }
    if (['product_lab', 'water_lab'].includes(r.form)) {
        const rows = r.data[r.form === 'product_lab' ? 'results' : 'micro'];
        requireCondition(rows.every((x) => x.conclusion === 'Pass' && x.correction_needed === 'No'), 'Resolve failed, untested or corrective-action laboratory results before approval.');
    }
    if (r.form === 'sieving')
        requireCondition(r.data.rows.every((x) => x.sieve_condition_before === 'Pass' && x.sieve_condition_after === 'Pass' && x.foreign_material_found === 'No'), 'Resolve sieve failures and foreign-material findings before approval.');
    if (r.form === 'premix_check')
        requireCondition(r.data.rows.every((x) => x.labelling === 'Pass' && x.sealing === 'Pass'), 'Premix labels and seals must pass.');
    if (r.form === 'premix_prep')
        requireCondition(r.data.checks.every((x) => x.preparation_verified === 'Pass'), 'All premix preparation checks must pass.');
    if (r.form === 'dispatch') {
        requireCondition(r.data.header.van_cleanliness === 'Clean with no bad smell' && r.data.header.delivery_staff_hygiene === 'Good / properly dressed', 'Resolve vehicle cleanliness and staff hygiene before dispatch.');
        requireCondition(r.data.rows.every((x) => x.label_seal_check === 'Pass'), 'All dispatched product labels and seals must pass.');
    }
}
function movement(s, lot, delta, r, type, customer) { lot.quantity = round(lot.quantity + delta); s.movements.unshift({ id: uid('MOV'), at: now(), lot: lot.id, delta, unit: lot.unit, type, record: r.id, batch: r.batch || lot.batch, customer }); }
function consume(s, r, rows, quantityKey, type) {
    const allocations = new Map();
    for (const row of rows) {
        const id = row.inventory_lot_id;
        allocations.set(id, round((allocations.get(id) || 0) + pos(row[quantityKey])));
    }
    for (const [id, qty] of allocations) {
        const lot = s.lots.find(x => x.id === id);
        requireCondition(lot, `Inventory lot ${id} was not found.`);
        requireCondition(lot.status === 'Released', `Lot ${id} is not released.`);
        requireCondition(lot.expiry >= today(), `Lot ${id} has expired.`);
        requireCondition(qty <= lot.quantity, `Insufficient stock in ${id}: ${lot.quantity} ${lot.unit} available.`);
        requireCondition(type === 'Issue' ? lot.type === 'Raw material' : lot.type === 'Finished goods', `Select a ${type === 'Issue' ? 'raw material' : 'finished goods'} lot.`);
        if (type === 'Dispatch')
            requireCondition(!batchBlocked(s, lot.batch), `Batch ${lot.batch} is held or has blocked inputs.`);
    }
    for (const row of rows) {
        const lot = s.lots.find(x => x.id === row.inventory_lot_id);
        if (type === 'Issue')
            requireCondition(lot.unit === row.unit, 'Issue unit must match the lot unit.');
        const qty = pos(row[quantityKey]);
        movement(s, lot, -qty, r, type, row.customer_name);
        if (type === 'Issue') {
            const b = s.batches.find(x => x.id === r.batch);
            b.inputs.push({ lot: lot.id, quantity: qty, unit: lot.unit, record: r.id });
            b.status = 'In progress';
        }
    }
}
function applyApproval(s, r) {
    const h = r.data.header || {}, rows = r.data.rows || [];
    if (r.form === 'receiving') {
        for (const row of r.data.lots) {
            requireCondition(row.expiry_date >= row.manufacturing_date, 'Expiry must be on or after manufacturing date.');
            requireCondition(!s.lots.some(x => x.type === 'Raw material' && x.material === h.material_name && x.code === row.lot_number && x.supplier === h.supplier_source), 'This material / supplier lot already exists.');
            const lot = { id: uid('RM'), code: row.lot_number, material: h.material_name, type: 'Raw material', quantity: 0, unit: row.unit, mfg: row.manufacturing_date, expiry: row.expiry_date, location: h.storage_location, supplier: h.supplier_source, status: 'Released', source: r.id, batch: '' };
            s.lots.push(lot);
            movement(s, lot, pos(row.quantity), r, 'Receipt');
        }
    }
    if (r.form === 'planning') {
        const id = h.batch_id.trim();
        requireCondition(!s.batches.some(b => b.id === id), 'Batch ID already exists.');
        s.batches.push({ id, product: h.product_name, code: h.product_code || '', target: pos(h.target_quantity_kg), date: h.scheduled_date, shift: h.shift, line: h.production_line, status: 'Planned', inputs: [], parents: [], order: r.id });
        r.batch = id;
    }
    if (formById[r.form].batch)
        requireCondition(s.batches.some(b => b.id === r.batch), 'The production batch does not exist.');
    if (r.form === 'issue') {
        requireCondition(!s.records.some(x => x.form === 'fg_receipt' && x.batch === r.batch && x.status === 'Approved'), 'This batch already has finished-goods receipts. Create a new batch for additional material.');
        requireCondition(!batchBlocked(s, r.batch), 'Cannot issue to a held or rejected batch.');
        consume(s, r, rows, 'issue_quantity', 'Issue');
    }
    if (r.form === 'fg_receipt') {
        requireCondition(!batchBlocked(s, r.batch), 'Batch or its input materials are on hold.');
        const missing = missingChecks(s, r.batch);
        requireCondition(!missing.length, `Complete these batch checks first: ${missing.map(x => formById[x].short).join(', ')}.`);
        const transfer = s.records.find(x => x.id === h.packing_transfer_record_id && x.form === 'packing_transfer' && x.batch === r.batch && x.status === 'Approved');
        requireCondition(transfer, 'Select an approved packing transfer for this batch.');
        const priorReceived = s.records.filter(x => x.id !== r.id && x.form === 'fg_receipt' && x.status === 'Approved' && x.data.header.packing_transfer_record_id === transfer.id).flatMap(x => x.data.rows).reduce((sum, x) => sum + num(x.quantity_packs), 0);
        const total = rows.reduce((a, x) => a + pos(x.quantity_packs), 0), produced = transfer.data.rows.reduce((a, x) => a + num(x.actual_produced_packs), 0);
        requireCondition(total + priorReceived <= produced, 'Warehouse receipt exceeds the remaining approved packing-transfer quantity.');
        for (const row of rows) {
            requireCondition(row.expiry_date >= row.manufacturing_date, 'Expiry must be on or after manufacturing date.');
            requireCondition(!s.lots.some(x => x.type === 'Finished goods' && x.batch === r.batch && x.code === row.lot_number), 'Finished-goods lot already exists for this batch.');
            const lot = { id: uid('FG'), code: row.lot_number, material: row.product_name, type: 'Finished goods', quantity: 0, unit: 'pack', mfg: row.manufacturing_date, expiry: row.expiry_date, location: h.storage_location, supplier: 'Internal production', status: 'Released', source: r.id, batch: r.batch };
            s.lots.push(lot);
            movement(s, lot, pos(row.quantity_packs), r, 'FG receipt');
        }
        s.batches.find(x => x.id === r.batch).status = 'Released';
    }
    if (r.form === 'dispatch')
        consume(s, r, rows, 'quantity_packs', 'Dispatch');
    if (r.form === 'nc') {
        const b = s.batches.find(x => x.id === r.batch);
        const dispositions = rows.map((x) => x.disposition);
        b.status = dispositions.includes('Scrap / reject') ? 'Rejected' : dispositions.every((x) => x === 'Release after correction') ? 'In progress' : 'Hold';
        for (const lot of s.lots.filter(x => x.batch === b.id || x.id === h.affected_material_lot))
            lot.status = b.status === 'Rejected' ? 'Rejected' : b.status === 'Hold' ? 'Hold' : 'Released';
    }
    if (r.form === 'nc_balance') {
        for (const row of rows) {
            const src = s.records.find(x => x.id === row.approved_nc_record_id && x.form === 'nc' && x.status === 'Approved');
            requireCondition(src && src.batch === row.source_batch, 'Choose an approved NC record matching the source batch.');
            requireCondition(row.destination_batch === r.batch, 'Destination batch must match the selected batch.');
            requireCondition(row.source_batch !== r.batch, 'A rework source cannot be its own destination.');
            const dest = s.batches.find(b => b.id === r.batch);
            const ancestor = (id, seen = new Set()) => { if (id === r.batch)
                return true; if (seen.has(id))
                return false; seen.add(id); return !!s.batches.find(b => b.id === id)?.parents.some(p => ancestor(p, seen)); };
            requireCondition(!ancestor(row.source_batch), 'Rework would create a circular batch relationship.');
            const eligible = src.data.rows.filter((x) => x.disposition === 'Approved rework').reduce((a, x) => a + num(x.affected_quantity_kg), 0);
            const used = s.records.filter(x => x.form === 'nc_balance' && x.status === 'Approved' && x.id !== r.id).flatMap(x => x.data.rows).filter((x) => x.approved_nc_record_id === src.id).reduce((a, x) => a + num(x.quantity_used_kg), 0);
            const current = rows.filter((x) => x.approved_nc_record_id === src.id).reduce((a, x) => a + pos(x.quantity_used_kg), 0);
            requireCondition(used + current <= eligible, 'Rework quantity exceeds its approved available balance.');
            if (!dest.parents.includes(row.source_batch))
                dest.parents.push(row.source_batch);
            row.available_quantity_kg = String(eligible - used);
            row.balance_kg = String(round(eligible - used - current));
        }
    }
}
export function execute(input, cmd) {
    const s = structuredClone(input);
    requireCondition(cmd && typeof cmd.type === 'string', 'Invalid action.');
    if (cmd.type === 'profile') {
        requireCondition(roles.some(x => x.id === cmd.role) || cmd.role === null, 'Unknown department profile.');
        s.profile = cmd.role;
        audit(s, cmd.role ? 'Entered department' : 'Left department', '', cmd.role || '');
        return s;
    }
    requireCondition(s.profile, 'Choose a department profile first.');
    if (cmd.type === 'master') {
        requireCondition(s.profile === 'admin', 'Only the administrator can edit master data.');
        const row = cmd.entry;
        requireCondition(row && ['Material', 'Product', 'Supplier', 'Customer', 'Equipment', 'Location', 'Recipe'].includes(row.category), 'Choose a master-data category.');
        requireCondition(typeof row.name === 'string' && row.name.trim().length > 0 && row.name.length <= 200, 'Enter a master-data name.');
        const entry = { id: row.id || uid('MD'), category: row.category, name: row.name.trim(), code: String(row.code || '').slice(0, 100), detail: String(row.detail || '').slice(0, 1000) };
        const index = s.masters.findIndex(x => x.id === entry.id);
        if (index >= 0)
            s.masters[index] = entry;
        else
            s.masters.push(entry);
        audit(s, 'Master data saved', entry.id, entry.name);
        return s;
    }
    if (cmd.type === 'save') {
        const def = formById[cmd.form];
        requireCondition(def, 'Unknown form.');
        requireCondition(canCreate(s.profile, def), 'This department cannot create or edit this form.');
        const existing = s.records.find(x => x.id === cmd.id);
        if (existing) {
            requireCondition(existing.form === cmd.form, 'Form type cannot change.');
            requireCondition(['Draft', 'Returned'].includes(existing.status), 'Only drafts and returned records can be edited.');
        }
        const data = validateShape(cmd.data, def);
        const batch = String(cmd.batch || '').trim().slice(0, 100);
        if (def.batch)
            requireCondition(!batch || s.batches.some(b => b.id === batch), 'Select an existing production batch.');
        const r = existing || { id: uid(def.code.replace(/[^A-Z]/g, '').slice(0, 6)), form: def.id, batch, status: 'Draft', data, createdAt: now(), updatedAt: now(), createdBy: person(s.profile), revision: 0, history: [], attachments: [] };
        r.data = data;
        r.batch = batch;
        r.status = 'Draft';
        r.updatedAt = now();
        r.revision++;
        r.history.unshift({ at: now(), by: person(s.profile), action: 'Saved draft', note: String(cmd.note || '').slice(0, 1000) });
        if (!existing)
            s.records.unshift(r);
        audit(s, 'Saved draft', r.id, def.name);
        return s;
    }
    const r = s.records.find(x => x.id === cmd.id);
    requireCondition(r, 'Record not found.');
    const rec = r;
    const def = formById[rec.form];
    const note = String(cmd.note || '').trim().slice(0, 2000);
    if (cmd.type === 'attachment') {
        requireCondition(canCreate(s.profile, def) && ['Draft', 'Returned'].includes(rec.status), 'Attachments can only be added to editable records by the owning department.');
        requireCondition(cmd.attachment && String(cmd.attachment.id).startsWith('ATT-'), 'Invalid attachment.');
        rec.attachments.push(cmd.attachment);
        audit(s, 'Attachment added', rec.id, cmd.attachment.name);
        return s;
    }
    if (cmd.type === 'submit') {
        requireCondition(canCreate(s.profile, def), 'This department cannot submit this form.');
        requireCondition(['Draft', 'Returned'].includes(rec.status), 'Only drafts can be submitted.');
        validateRecord(rec);
        rec.status = 'Submitted';
        if (rec.form === 'nc') {
            const b = s.batches.find(x => x.id === rec.batch);
            requireCondition(b, 'Select an existing batch.');
            b.status = 'Hold';
            for (const lot of s.lots.filter(x => x.batch === rec.batch || x.id === rec.data.header.affected_material_lot))
                lot.status = 'Hold';
        }
    }
    else if (['approve', 'return', 'reject'].includes(cmd.type)) {
        requireCondition(canReview(s.profile, def), 'This department cannot review this form.');
        requireCondition(rec.status === 'Submitted', 'Only submitted records can be reviewed.');
        requireCondition(note, 'Enter a review note.');
        if (cmd.type === 'approve') {
            validateRecord(rec);
            qualityGate(rec);
            applyApproval(s, rec);
            rec.status = 'Approved';
            rec.data.sign = { ...(rec.data.sign || {}), approved_by: person(s.profile) };
        }
        else
            rec.status = cmd.type === 'return' ? 'Returned' : 'Rejected';
    }
    else if (cmd.type === 'revise') {
        requireCondition(canCreate(s.profile, def), 'This department cannot prepare a correction.');
        requireCondition(['Approved', 'Rejected'].includes(rec.status), 'Only finalized records need a correction copy.');
        requireCondition(note, 'Enter a correction reason.');
        requireCondition(!['receiving', 'planning', 'issue', 'fg_receipt', 'dispatch', 'nc_balance'].includes(rec.form), 'Posted stock/order records are locked. Record an NC or a new valid transaction; do not duplicate a posted transaction.');
        const copy = structuredClone(rec);
        copy.id = uid('REV');
        copy.supersedes = rec.id;
        copy.status = 'Draft';
        copy.createdAt = now();
        copy.updatedAt = now();
        copy.revision = 0;
        copy.history = [{ at: now(), by: person(s.profile), action: 'Correction copy', note: `From ${rec.id}: ${note}` }];
        s.records.unshift(copy);
        audit(s, 'Correction copy created', copy.id, `Original ${rec.id}: ${note}`);
        return s;
    }
    else
        throw Error('Unsupported action.');
    rec.updatedAt = now();
    rec.history.unshift({ at: now(), by: person(s.profile), action: cmd.type, note });
    audit(s, cmd.type, rec.id, note || def.name);
    return s;
}
function demoRecord(def, status, id, batch) {
    const data = blankData(def);
    for (const sec of def.sections) {
        const rows = sec.repeat ? data[sec.id] : [data[sec.id]];
        for (const row of rows) {
            for (const f of sec.fields) {
                if (row[f.key] !== undefined)
                    continue;
                row[f.key] = f.type === 'date' ? '2026-10-05' : f.type === 'time' ? '09:00' : f.type === 'number' ? '1' : f.type === 'select' ? (f.options.includes('Pass') ? 'Pass' : f.options.includes('No') ? 'No' : f.options[0]) : f.required ? 'Demo entry' : '';
            }
        }
    }
    return { id, form: def.id, batch, status, data, createdAt: '2026-10-05T02:00:00.000Z', updatedAt: '2026-10-05T05:30:00.000Z', createdBy: person(def.department), revision: 1, history: [{ at: '2026-10-05T05:30:00.000Z', by: 'Demo Administrator', action: 'Sample record', note: 'Synthetic showcase data; not a transcription of factory records.' }], attachments: [] };
}
export function seed() {
    const batch = 'DEMO-HSS-1005-01';
    const s = { schemaVersion: 1, profile: null, records: [], lots: [], batches: [], movements: [], audit: [], masters: [], settings: { plant: 'Food Business · Demonstration Plant', timezone: 'Asia/Dhaka', requiredChecks: requiredBatchChecks }, seededAt: now() };
    for (const def of forms) {
        const status = ['receiving', 'vegetable', 'sieving', 'premix_check', 'premix_prep', 'water_lab', 'nc', 'nc_balance', 'planning'].includes(def.id) ? 'Draft' : 'Approved';
        s.records.push(demoRecord(def, status, `DEMO-${def.id.toUpperCase()}`, def.batch ? batch : ''));
    }
    const get = (id) => s.records.find(r => r.form === id);
    get('receiving').data.header = { raw_material_type: 'Meat', material_name: 'Chicken meat', receiving_date: '2026-10-05', po_number: 'DEMO-PO-104', challan_number: 'DEMO-CH-104', supplier_source: 'Demo Poultry Supplier', qc_inspector: 'QC Officer', truck_car_number: 'DEMO-VAN-02', sampling_number: '4', storage_location: 'Chiller A' };
    get('receiving').data.lots = [{ lot_number: 'DEMO-RM-1005-B', manufacturing_date: '2026-10-05', expiry_date: '2026-10-09', quantity: '120', unit: 'kg', arrival_temperature_1_c: '3.4', arrival_temperature_2_c: '3.7', arrival_temperature_3_c: '3.5', arrival_temperature_4_c: '3.6' }];
    get('receiving').data.inspection.forEach((x) => { x.conforming = 'Yes'; x.sample_1 = 'Pass'; });
    get('receiving').data.decision = { quantity_check: 'On PO required', quality_result: 'Pass', action_required: 'None' };
    get('receiving').status = 'Submitted';
    get('planning').data.header = { batch_id: 'DEMO-HSS-1005-02', product_name: 'Chicken Hot Sausage', product_code: 'DEMO-HSS', target_quantity_kg: '70', scheduled_date: '2026-10-05', shift: 'Day', production_line: 'Sausage Line 1', recipe_version: 'DEMO-1', priority: 'Normal' };
    get('planning').data.requirements = [{ material: 'Chicken meat', required_quantity: '30', unit: 'kg' }, { material: 'Chicken skin', required_quantity: '5', unit: 'kg' }, { material: 'Prepared premix', required_quantity: '13.4', unit: 'kg' }, { material: 'Water / ice', required_quantity: '21.6', unit: 'kg' }];
    const raw = [['RM-DEMO-001', 'DEMO-MEAT-01', 'Chicken meat', 450, 30, 'Demo Poultry Supplier'], ['RM-DEMO-002', 'DEMO-SKIN-01', 'Chicken skin', 100, 5, 'Demo Poultry Supplier'], ['RM-DEMO-003', 'DEMO-PX-01', 'Prepared premix', 60, 13.4, 'Demo Ingredients Supplier'], ['RM-DEMO-004', 'DEMO-WATER-01', 'Water / ice', 200, 21.6, 'Demo Utilities']];
    const b = { id: batch, product: 'Chicken Hot Sausage', code: 'DEMO-HSS', target: 70, date: '2026-10-05', shift: 'Day', line: 'Sausage Line 1', status: 'Released', inputs: [], parents: [], order: 'DEMO-ORDER-001' };
    s.batches.push(b);
    for (const [id, code, material, received, used, supplier] of raw) {
        const lot = { id: String(id), code: String(code), material: String(material), type: 'Raw material', quantity: Number(received) - Number(used), unit: 'kg', mfg: '2026-10-05', expiry: '2027-10-05', location: 'Chiller A', supplier: String(supplier), status: 'Released', source: 'DEMO-OPENING-STOCK', batch: '' };
        s.lots.push(lot);
        s.movements.push({ id: uid('MOV'), at: '2026-10-05T02:00:00Z', lot: lot.id, delta: Number(received), unit: 'kg', type: 'Opening stock', record: 'DEMO-OPENING-STOCK', batch: '' }, { id: uid('MOV'), at: '2026-10-05T03:00:00Z', lot: lot.id, delta: -Number(used), unit: 'kg', type: 'Issue', record: get('issue').id, batch });
        b.inputs.push({ lot: lot.id, quantity: Number(used), unit: 'kg', record: get('issue').id });
    }
    get('issue').data.rows = b.inputs.map(x => ({ inventory_lot_id: x.lot, issue_quantity: String(x.quantity), unit: x.unit }));
    get('sausage').data.header.product_name = 'Chicken Hot Sausage';
    get('sausage').data.ingredients = b.inputs.map(x => ({ batch_number: batch, start_time: '08:00', finish_time: '08:09', speed: '2', ingredient: s.lots.find(l => l.id === x.lot).material, recipe_quantity_kg: String(x.quantity), actual_quantity_kg: String(x.quantity), source_lot: x.lot, temperature_c: '6.4' }));
    get('steam').data.header = { product_name: 'Chicken Hot Sausage', box_number: 'SB-01', cycle_id: 'DEMO-CYCLE-01', date: '2026-10-05', batches_in_cycle: batch, input_kg: '70', output_total_kg: '63', approved_cooking_specification: 'Demonstration only - validate actual factory specification' };
    get('steam').data.readings = [{ step_time: '01', setting_temperature_c: '55', actual_time: '09:00', actual_ambient_temperature_c: '55', core_temperature_c: '30' }, { step_time: '02', setting_temperature_c: '65', actual_time: '09:15', actual_ambient_temperature_c: '65', core_temperature_c: '60' }, { step_time: '03', setting_temperature_c: '85', actual_time: '09:25', actual_ambient_temperature_c: '85', core_temperature_c: '80' }];
    get('steam').data.verification.cycle_result = 'Pass';
    get('metal').data.rows = [{ time: '10:30', product_name: 'Chicken Hot Sausage', program_number: 'DEMO-01', lot_batch: batch, quantity_packs: '63', fe_test: 'Pass', non_fe_test: 'Pass', sus_test: 'Pass', test_arm_reject: 'Pass' }];
    get('metal').data.verification.overall_result = 'Pass';
    get('product_lab').data.header.sample_description = 'Demo Chicken Hot Sausage';
    get('product_lab').data.results.forEach((x) => { x.result = x.test_parameter === 'pH' ? '7.04' : 'ND'; x.conclusion = 'Pass'; x.correction_needed = 'No'; x.approved_standard = 'Demo - QC verification required'; });
    get('packing_transfer').data.rows = [{ product_code: 'DEMO-HSS', product_name: 'Chicken Hot Sausage', pack_size: '1000 g', batch_lot: batch, prepared_packs: '63', price_label: 'Yes', actual_produced_packs: '63', transferred_by_pd: 'Production Operator', received_by_wh: 'Warehouse Officer' }];
    get('fg_receipt').data.header = { date: '2026-10-05', station: 'FG', storage_location: 'Freezer 1', packing_transfer_record_id: get('packing_transfer').id };
    get('fg_receipt').data.rows = [{ product_code: 'DEMO-HSS', product_name: 'Chicken Hot Sausage', size_g: '1000', lot_number: 'DEMO-FG-01', quantity_packs: '63', manufacturing_date: '2026-10-05', expiry_date: '2027-04-05' }];
    s.lots.push({ id: 'FG-DEMO-001', code: 'DEMO-FG-01', material: 'Chicken Hot Sausage', type: 'Finished goods', quantity: 51, unit: 'pack', mfg: '2026-10-05', expiry: '2027-04-05', location: 'Freezer 1', supplier: 'Internal production', status: 'Released', source: get('fg_receipt').id, batch });
    get('dispatch').data.header = { van_number: 'DEMO-VAN-01', date: '2026-10-05', route: 'Dhaka demo route', driver_name: 'Demo Driver', preparation_start: '10:00', preparation_finish: '10:30', van_cleanliness: 'Clean with no bad smell', vehicle_temperature_range: '-20 to -30 C', ice_pack_as_standard: 'Yes', delivery_staff_hygiene: 'Good / properly dressed' };
    get('dispatch').data.rows = [{ customer_name: 'Demo Customer A', inventory_lot_id: 'FG-DEMO-001', product_name: 'Chicken Hot Sausage', product_size: '1000 g', product_code: 'DEMO-HSS', manufacturing_date: '2026-10-05', expiry_date: '2027-04-05', lot_number: 'DEMO-FG-01', quantity_packs: '12', label_seal_check: 'Pass', product_temperature_c: '-18' }];
    s.movements.push({ id: uid('MOV'), at: '2026-10-05T04:00:00Z', lot: 'FG-DEMO-001', delta: 63, unit: 'pack', type: 'FG receipt', record: get('fg_receipt').id, batch }, { id: uid('MOV'), at: '2026-10-05T05:00:00Z', lot: 'FG-DEMO-001', delta: -12, unit: 'pack', type: 'Dispatch', record: get('dispatch').id, batch, customer: 'Demo Customer A' });
    get('nc').data.header = { product_name: 'Chicken Hot Sausage', report_date: '2026-10-05', location: 'Linking area', stage: 'Work in process', occurrence: 'During preparation', qc_operator: 'QC Officer' };
    get('nc').data.rows = [{ nc_characteristic: 'Demonstration of a linking defect', affected_quantity_kg: '2', disposition: 'Hold', correction_method: 'Enter QC-authorized action' }];
    get('nc_balance').data.rows = [{ approved_nc_record_id: '', source_batch: '', nc_product_name: 'Chicken Hot Sausage', quantity_used_kg: '1', destination_product: 'Chicken Hot Sausage', destination_batch: batch }];
    const masters = [['Product', 'Chicken Hot Sausage', 'DEMO-HSS', 'Sausage Line 1'], ['Material', 'Chicken meat', 'DEMO-MEAT', 'kg'], ['Material', 'Chicken skin', 'DEMO-SKIN', 'kg'], ['Material', 'Prepared premix', 'DEMO-PX', 'kg'], ['Material', 'Water / ice', 'DEMO-WATER', 'kg'], ['Supplier', 'Demo Poultry Supplier', 'SUP-01', 'Sample supplier'], ['Customer', 'Demo Customer A', 'CUS-01', 'Dhaka'], ['Equipment', 'Steam Box 1', 'SB-01', 'Cooking'], ['Equipment', 'Metal Detector 1', 'MD-01', 'Packing'], ['Location', 'Chiller A', 'CH-01', 'Raw material'], ['Location', 'Freezer 1', 'FR-01', 'Finished goods'], ['Recipe', 'Demo sausage recipe', 'DEMO-1', 'Sample formulation - factory validation required']];
    s.masters = masters.map(([category, name, code, detail]) => ({ id: uid('MD'), category, name, code, detail }));
    s.audit = s.records.filter(r => r.status === 'Approved').slice(0, 8).map(r => ({ id: uid('AUD'), at: r.updatedAt, by: 'Demo Administrator', action: 'Sample approved record', record: r.id, note: formById[r.form].name }));
    return s;
}
// Intentionally published showcase credentials; never use these for factory access.
export const demoPassword = 'Demo123!';
export const demoAccounts = roles.map(role => ({ id: role.id, username: `${role.id}.demo`, name: role.name }));
export function authenticateDemo(username, password) {
    if (typeof username !== 'string' || password !== demoPassword)
        return null;
    return demoAccounts.find(a => a.username === username.trim().toLowerCase())?.id ?? null;
}
const allowedOrigins = ['https://jahidhrk.github.io', 'http://localhost:5173', 'http://127.0.0.1:5173'];
const bucket = 'factory-attachments';
class HttpError extends Error {
    status;
    constructor(status, message) {
        super(message);
        this.status = status;
    }
}
function settings() {
    const url = Deno.env.get('SUPABASE_URL');
    const keys = JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS') || '{}');
    const key = keys.default || Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
    if (!url || !key)
        throw new HttpError(503, 'Backend configuration is incomplete.');
    return { url, key };
}
async function service(path, init = {}) {
    const { url, key } = settings();
    const headers = new Headers(init.headers);
    headers.set('apikey', key);
    headers.set('Authorization', `Bearer ${key}`);
    const res = await fetch(url + path, { ...init, headers });
    if (!res.ok) {
        console.error('Supabase operation failed', res.status, path.split('?')[0]);
        throw new HttpError(503, 'Database or storage is not ready. Complete the Supabase setup instructions.');
    }
    return res;
}
const jsonHeaders = { 'Content-Type': 'application/json' };
async function hash(value) { const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return [...new Uint8Array(bytes)].map(b => b.toString(16).padStart(2, '0')).join(''); }
async function readWorkspace() {
    const rows = await (await service('/rest/v1/factory_workspace?id=eq.demo&select=payload,version')).json();
    if (rows[0])
        return rows[0];
    await service('/rest/v1/factory_workspace', { method: 'POST', headers: { ...jsonHeaders, Prefer: 'resolution=ignore-duplicates' }, body: JSON.stringify({ id: 'demo', payload: seed(), version: 0 }) });
    const again = await (await service('/rest/v1/factory_workspace?id=eq.demo&select=payload,version')).json();
    if (!again[0])
        throw new HttpError(503, 'Unable to initialize the workspace.');
    return again[0];
}
async function session(req) {
    const token = req.headers.get('X-Demo-Session') || '';
    if (!/^[a-f0-9]{64}$/.test(token))
        throw new HttpError(401, 'Sign in with your demo account.');
    const tokenHash = await hash(token);
    const rows = await (await service(`/rest/v1/factory_sessions?token_hash=eq.${tokenHash}&select=department,expires_at`)).json();
    if (!rows[0] || new Date(rows[0].expires_at).getTime() <= Date.now())
        throw new HttpError(401, 'Your session expired. Sign in again.');
    return { role: rows[0].department, tokenHash };
}
function data(row, role) { return { state: { ...row.payload, profile: role }, version: row.version, user: { name: roles.find(r => r.id === role).person, email: `${role}.demo` } }; }
async function persist(state, version) {
    const res = await service(`/rest/v1/factory_workspace?id=eq.demo&version=eq.${version}`, { method: 'PATCH', headers: { ...jsonHeaders, Prefer: 'return=representation' }, body: JSON.stringify({ payload: { ...state, profile: null }, version: version + 1, updated_at: new Date().toISOString() }) });
    const rows = await res.json();
    if (rows.length !== 1)
        throw new HttpError(409, 'Another department saved changes first. Refresh and try again.');
    return { payload: rows[0].payload, version: rows[0].version };
}
async function body(req) { const raw = await req.text(); if (raw.length > 300000)
    throw new HttpError(413, 'Request too large.'); try {
    return JSON.parse(raw);
}
catch {
    throw new HttpError(400, 'Invalid request.');
} }
export async function handle(req) {
    const origin = req.headers.get('Origin') || '';
    const cors = { 'Access-Control-Allow-Headers': 'apikey,content-type,x-demo-session', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS', 'Vary': 'Origin', 'Cache-Control': 'no-store' };
    if (origin && allowedOrigins.includes(origin))
        cors['Access-Control-Allow-Origin'] = origin;
    const reply = (payload, status = 200) => Response.json(payload, { status, headers: cors });
    if (origin && !allowedOrigins.includes(origin))
        return reply({ error: 'This website is not authorized to use this demo.' }, 403);
    if (req.method === 'OPTIONS')
        return new Response(null, { status: 204, headers: cors });
    try {
        const url = new URL(req.url), endpoint = url.pathname.split('/').at(-1);
        if (endpoint === 'health' && req.method === 'GET')
            return reply({ status: 'ok', application: 'factory-operations' });
        if (endpoint === 'login' && req.method === 'POST') {
            const input = await body(req), command = input.command || input;
            const role = authenticateDemo(command.username, command.password);
            if (!role)
                throw new HttpError(401, 'Incorrect demo user ID or password.');
            const row = await readWorkspace();
            // Token values never enter the database, audit log or source control.
            const token = [...crypto.getRandomValues(new Uint8Array(32))].map(b => b.toString(16).padStart(2, '0')).join('');
            await service(`/rest/v1/factory_sessions?expires_at=lt.${encodeURIComponent(new Date().toISOString())}`, { method: 'DELETE' });
            await service('/rest/v1/factory_sessions', { method: 'POST', headers: jsonHeaders, body: JSON.stringify({ token_hash: await hash(token), department: role, expires_at: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString() }) });
            return reply({ ...data(row, role), token });
        }
        const account = await session(req);
        if (endpoint === 'logout' && req.method === 'POST') {
            await service(`/rest/v1/factory_sessions?token_hash=eq.${account.tokenHash}`, { method: 'DELETE' });
            return reply({ signedOut: true });
        }
        const row = await readWorkspace();
        if (endpoint === 'operations' && req.method === 'GET')
            return reply(data(row, account.role));
        if (endpoint === 'operations' && req.method === 'POST') {
            const input = await body(req);
            if (input.version !== row.version)
                throw new HttpError(409, 'Workspace changed. Refresh and try again.');
            if (['profile', 'attachment'].includes(input.command?.type))
                throw new HttpError(400, 'Use the dedicated login or attachment endpoint.');
            const next = execute({ ...row.payload, profile: account.role }, input.command);
            return reply(data(await persist(next, row.version), account.role));
        }
        if (endpoint === 'attachments' && req.method === 'POST') {
            if (Number(req.headers.get('Content-Length') || 0) > 9 * 1024 * 1024)
                throw new HttpError(413, 'Upload a file up to 8 MB.');
            const form = await req.formData(), file = form.get('file'), recordId = String(form.get('record') || '');
            if (!(file instanceof File) || !['application/pdf', 'image/jpeg', 'image/png'].includes(file.type) || file.size > 8 * 1024 * 1024)
                throw new HttpError(400, 'Upload a PDF, JPG or PNG up to 8 MB.');
            const id = uid('ATT'), objectPath = `/storage/v1/object/${bucket}/${id}`;
            const next = execute({ ...row.payload, profile: account.role }, { type: 'attachment', id: recordId, attachment: { id, name: file.name.slice(0, 200), type: file.type, size: file.size } });
            await service(objectPath, { method: 'POST', headers: { 'Content-Type': file.type }, body: await file.arrayBuffer() });
            try {
                return reply(data(await persist(next, row.version), account.role));
            }
            catch (e) {
                await service(`/storage/v1/object/${bucket}`, { method: 'DELETE', headers: jsonHeaders, body: JSON.stringify({ prefixes: [id] }) });
                throw e;
            }
        }
        if (endpoint === 'attachments' && req.method === 'GET') {
            const id = url.searchParams.get('id') || '';
            if (!/^ATT-[A-F0-9]{8}$/.test(id) || !row.payload.records.some(r => r.attachments.some(a => a.id === id)))
                throw new HttpError(404, 'Attachment not found.');
            const res = await service(`/storage/v1/object/authenticated/${bucket}/${id}`);
            return new Response(res.body, { headers: { ...cors, 'Content-Type': res.headers.get('Content-Type') || 'application/octet-stream', 'Content-Disposition': 'attachment', 'X-Content-Type-Options': 'nosniff' } });
        }
        return reply({ error: 'Endpoint not found.' }, 404);
    }
    catch (e) {
        if (e instanceof HttpError)
            return reply({ error: e.message }, e.status);
        return reply({ error: e instanceof Error ? e.message : 'Request failed.' }, 400);
    }
}
Deno.serve(handle);
